SHELL := bash
.SHELLFLAGS := -eu -o pipefail -c
.DEFAULT_GOAL := all

CC := clang
CSTD := c23
P := coffee
SRC_DIR := src
BIN_DIR := bin

COMMANDS_SRCS := $(wildcard $(SRC_DIR)/commands/*.c)

# Unity build — single translation unit
UNITY_FILE := $(BIN_DIR)/coffee_unity.c
UNITY_OBJ  := $(BIN_DIR)/coffee_unity.o
TARGET     := $(BIN_DIR)/$(P)

UNITY_CORE_SRCS := \
	$(SRC_DIR)/cmdline.c \
	$(SRC_DIR)/toolcheck.c \
	$(SRC_DIR)/manifest.c \
	$(SRC_DIR)/registry.c \
	$(SRC_DIR)/project.c \
	$(SRC_DIR)/coffee_features.c \
	$(SRC_DIR)/build.c \
	$(SRC_DIR)/lockfile.c \
	$(SRC_DIR)/version.c \
	$(SRC_DIR)/dep_graph.c \
	$(SRC_DIR)/coffee.c

UNITY_ALL_SRCS := $(UNITY_CORE_SRCS) $(sort $(COMMANDS_SRCS))

# Suppress noisy clang -Weverything warnings that are not bugs in C23
WNO := \
	-Wno-pre-c23-compat \
	-Wno-pre-c11-compat \
	-Wno-declaration-after-statement \
	-Wno-disabled-macro-expansion \
	-Wno-implicit-void-ptr-cast \
	-Wno-padded \
	-Wno-unsafe-buffer-usage

CFLAGS_COMMON := -g -Weverything -O3 -std=$(CSTD) $(WNO)

# Release mode: strip debug symbols
ifdef RELEASE
  CFLAGS_COMMON := $(filter-out -g, $(CFLAGS_COMMON))
endif
# Debug mode: no optimization, add DEBUG define
ifdef DEBUG
  CFLAGS_COMMON := $(subst -O3, -O0, $(CFLAGS_COMMON))
  CFLAGS_COMMON += -DDEBUG
endif
# External CFLAGS overlay (feature flags from coffee build)
CFLAGS_COMMON += $(CFLAGS_EXTRA)
CFLAGS_COMMON += -D_GNU_SOURCE -include $(SRC_DIR)/compat_limits.h -iquote$(SRC_DIR) -isysteminclude -iquoteinclude/sds
LDFLAGS := -static

MDBOOK := $(if $(wildcard ./mdbook),./mdbook,mdbook)

SKELETONS_H := $(SRC_DIR)/skeletons.h

$(SKELETONS_H): $(wildcard skeletons/*)
	./scripts/embed_skeletons.sh skeletons $@

# Generate the unity file
$(UNITY_FILE): $(UNITY_ALL_SRCS)
	@mkdir -p $(BIN_DIR)
	@{ \
		echo "// Unity build - single compilation unit"; \
		echo "// Auto-generated by Makefile. Do not edit."; \
		echo ""; \
		echo "#pragma clang diagnostic push"; \
		echo "#pragma clang diagnostic ignored \"-Weverything\""; \
		echo "#pragma push_macro(\"malloc\")"; \
		echo "#pragma push_macro(\"calloc\")"; \
		echo "#pragma push_macro(\"realloc\")"; \
		echo "#pragma push_macro(\"free\")"; \
		echo "#include \"../src/toml.c\""; \
		echo "#pragma pop_macro(\"malloc\")"; \
		echo "#pragma pop_macro(\"calloc\")"; \
		echo "#pragma pop_macro(\"realloc\")"; \
		echo "#pragma pop_macro(\"free\")"; \
		echo "#pragma clang diagnostic pop"; \
		echo ""; \
		echo "#pragma clang diagnostic push"; \
		echo "#pragma clang diagnostic ignored \"-Weverything\""; \
		echo "#include \"../src/sds.c\""; \
		echo "#pragma clang diagnostic pop"; \
		echo ""; \
		for f in $(UNITY_CORE_SRCS); do \
			echo "#include \"../$$f\""; \
		done; \
		for f in $(sort $(COMMANDS_SRCS)); do \
			echo "#include \"../$$f\""; \
		done; \
	} > $@

$(UNITY_OBJ): $(UNITY_FILE) $(SKELETONS_H)
	$(CC) $(CFLAGS_COMMON) -c $(UNITY_FILE) -o $@

$(TARGET): $(UNITY_OBJ)
	@mkdir -p $(BIN_DIR)
	$(CC) $(LDFLAGS) -o $@ $(UNITY_OBJ)

# Test runner — project code as unity (no main), test files compiled separately
TEST_SUPPORT_FILE := $(BIN_DIR)/tests/test_support_unity.c
TEST_SUPPORT_OBJ  := $(BIN_DIR)/tests/test_support_unity.o
TEST_COFFEE_OBJ   := $(BIN_DIR)/tests/coffee_test_runner.o
TEST_RUNNER       := $(BIN_DIR)/tests/runner
TEST_SRCS         := $(wildcard tests/*.c)
TEST_OBJS         := $(TEST_SRCS:tests/%.c=$(BIN_DIR)/tests/%.o)

TEST_SUPPORT_SRCS := $(filter-out $(SRC_DIR)/coffee.c, $(UNITY_CORE_SRCS)) $(sort $(COMMANDS_SRCS))

$(TEST_SUPPORT_FILE): $(TEST_SUPPORT_SRCS)
	@mkdir -p $(BIN_DIR)/tests
	@{ \
		echo "// Test support unity build - project code without main"; \
		echo "// Auto-generated by Makefile. Do not edit."; \
		echo ""; \
		echo "#pragma clang diagnostic push"; \
		echo "#pragma clang diagnostic ignored \"-Weverything\""; \
		echo "#pragma push_macro(\"malloc\")"; \
		echo "#pragma push_macro(\"calloc\")"; \
		echo "#pragma push_macro(\"realloc\")"; \
		echo "#pragma push_macro(\"free\")"; \
		echo "#include \"../src/toml.c\""; \
		echo "#pragma pop_macro(\"malloc\")"; \
		echo "#pragma pop_macro(\"calloc\")"; \
		echo "#pragma pop_macro(\"realloc\")"; \
		echo "#pragma pop_macro(\"free\")"; \
		echo "#pragma clang diagnostic pop"; \
		echo ""; \
		echo "#pragma clang diagnostic push"; \
		echo "#pragma clang diagnostic ignored \"-Weverything\""; \
		echo "#include \"../src/sds.c\""; \
		echo "#pragma clang diagnostic pop"; \
		echo ""; \
		for f in $(TEST_SUPPORT_SRCS); do \
			echo "#include \"../$$f\""; \
		done; \
	} > $@

$(TEST_SUPPORT_OBJ): $(TEST_SUPPORT_FILE) $(SKELETONS_H)
	$(CC) $(CFLAGS_COMMON) -c $(TEST_SUPPORT_FILE) -o $@

$(TEST_COFFEE_OBJ): $(SRC_DIR)/coffee.c
	@mkdir -p $(BIN_DIR)/tests
	$(CC) $(CFLAGS_COMMON) -DCOFFEE_TEST_RUNNER -c $< -o $@

$(BIN_DIR)/tests/%.o: tests/%.c tests/test_framework.h
	@mkdir -p $(BIN_DIR)/tests
	$(CC) $(CFLAGS_COMMON) -DCOFFEE_TEST_RUNNER -Itests -c $< -o $@

$(TEST_RUNNER): $(TEST_OBJS) $(TEST_SUPPORT_OBJ) $(TEST_COFFEE_OBJ)
	@mkdir -p $(BIN_DIR)/tests
	$(CC) $(LDFLAGS) -o $@ $^

all: $(TARGET)

bootstrap:
	@mkdir -p include/sds
	@echo "Checking dependencies..."
	@if [ ! -f src/toml.c ]; then \
		curl -fsSL https://raw.githubusercontent.com/cktan/tomlc99/master/toml.c -o src/toml.c; \
	fi
	@if [ ! -f include/toml.h ]; then \
		curl -fsSL https://raw.githubusercontent.com/cktan/tomlc99/master/toml.h -o include/toml.h; \
	fi
	@if [ ! -f include/sds/sds.h ]; then \
		curl -fsSL https://raw.githubusercontent.com/antirez/sds/master/sds.h -o include/sds/sds.h; \
	fi
	@if [ ! -f include/sds/sdsalloc.h ]; then \
		curl -fsSL https://raw.githubusercontent.com/antirez/sds/master/sdsalloc.h -o include/sds/sdsalloc.h; \
	fi
	@if [ ! -f src/sds.c ]; then \
		curl -fsSL https://raw.githubusercontent.com/antirez/sds/master/sds.c -o src/sds.c; \
	fi
	@echo "Dependencies ready."

clean:
	rm -rf $(BIN_DIR)

format:
	clang-format -i $(SRC_DIR)/*.c $(SRC_DIR)/*.h $(SRC_DIR)/commands/*.c tests/*.c tests/*.h

test: $(TEST_RUNNER)
	@if [ -n "$(TEST_FILTER)" ]; then \
		$(TEST_RUNNER) "$(TEST_FILTER)"; \
	else \
		$(TEST_RUNNER); \
	fi

tidy:
	find src tests -name "*.c" -print0 | xargs -0 -I{} clang-tidy --quiet --warnings-as-errors='*' {} -- -Isrc -Iinclude -Iinclude/sds -I. -Ideps -std=c23 -D_GNU_SOURCE

INSTALL_DIR ?= $(HOME)/.coffee/bin
install: $(TARGET)
	@mkdir -p $(INSTALL_DIR)
	cp $(TARGET) $(INSTALL_DIR)/$(P)
	@echo "Installed $(P) to $(INSTALL_DIR)/$(P)"

docs:
	@$(MDBOOK) build

serve:
	$(MDBOOK) serve

release:
	sed -i 's/\(version = "[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}\.\)[0-9T]\{1,\}/\1'"$$(date +%Y%m%dT%H%M)"'/' Coffee.toml
	@echo "Updated Coffee.toml version to include timestamp $$(date +%Y%m%dT%H%M)"

# --------------------------------------------------------------------
# Fuzz targets — libFuzzer instrumented binaries
# --------------------------------------------------------------------
FUZZ_DIR := $(BIN_DIR)/fuzz
FUZZ_SRCS := $(wildcard fuzz/fuzz_*.c)
FUZZ_BINS := $(FUZZ_SRCS:fuzz/fuzz_%.c=$(FUZZ_DIR)/fuzz_%)

FUZZ_SUPPORT_FILE := $(FUZZ_DIR)/fuzz_support_unity.c
FUZZ_SUPPORT_OBJ  := $(FUZZ_DIR)/fuzz_support_unity.o

# Same sources as test support (all project code minus coffee.c main())
FUZZ_SUPPORT_SRCS := $(TEST_SUPPORT_SRCS)

# Sanitizer flags: fuzzer-no-link for the unity object, fuzzer for final link
FUZZ_CFLAGS := -g -O1 -fsanitize=fuzzer-no-link,address -std=$(CSTD) $(WNO) \
	-D_GNU_SOURCE -include $(SRC_DIR)/compat_limits.h -iquote$(SRC_DIR) -isysteminclude -iquoteinclude/sds

$(FUZZ_SUPPORT_FILE): $(FUZZ_SUPPORT_SRCS)
	@mkdir -p $(FUZZ_DIR)
	@{ \
		echo "// Fuzz support unity build"; \
		echo "// Auto-generated by Makefile. Do not edit."; \
		echo ""; \
		echo "#pragma clang diagnostic push"; \
		echo "#pragma clang diagnostic ignored \"-Weverything\""; \
		echo "#pragma push_macro(\"malloc\")"; \
		echo "#pragma push_macro(\"calloc\")"; \
		echo "#pragma push_macro(\"realloc\")"; \
		echo "#pragma push_macro(\"free\")"; \
		echo "#include \"../src/toml.c\""; \
		echo "#pragma pop_macro(\"malloc\")"; \
		echo "#pragma pop_macro(\"calloc\")"; \
		echo "#pragma pop_macro(\"realloc\")"; \
		echo "#pragma pop_macro(\"free\")"; \
		echo "#pragma clang diagnostic pop"; \
		echo ""; \
		echo "#pragma clang diagnostic push"; \
		echo "#pragma clang diagnostic ignored \"-Weverything\""; \
		echo "#include \"../src/sds.c\""; \
		echo "#pragma clang diagnostic pop"; \
		echo ""; \
		for f in $(FUZZ_SUPPORT_SRCS); do \
			echo "#include \"../$$f\""; \
		done; \
	} > $@

$(FUZZ_SUPPORT_OBJ): $(FUZZ_SUPPORT_FILE) $(SKELETONS_H)
	$(CC) $(FUZZ_CFLAGS) -c $(FUZZ_SUPPORT_FILE) -o $@

$(FUZZ_DIR)/fuzz_%: fuzz/fuzz_%.c $(FUZZ_SUPPORT_OBJ)
	@mkdir -p $(FUZZ_DIR)
	$(CC) $(FUZZ_CFLAGS) -fsanitize=fuzzer,address $< $(FUZZ_SUPPORT_OBJ) -o $@

fuzz: $(FUZZ_BINS)

.PHONY: all bootstrap clean format test tidy install docs serve release fuzz
