#include "../coffee.h"
#include "../manifest.h"
#include "../project.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <toml.h>
#include <unistd.h>

/* State for toml_str_def — use sds for thread safety and no static buffer */
typedef struct {
	sds project_name;
	sds output_dir;
	sds input_dirs;
	sds exclude_patterns;
} doc_settings_t;

static void doc_settings_read(doc_settings_t *cfg, toml_table_t *doc_tab, const char *def_name, const char *def_out,
                              const char *def_input)
{
	memset(cfg, 0, sizeof(*cfg));
	if (doc_tab == nullptr) {
		cfg->project_name     = sdsnew(def_name);
		cfg->output_dir       = sdsnew(def_out);
		cfg->input_dirs       = sdsnew(def_input);
		cfg->exclude_patterns = sdsnew("");
		return;
	}

	toml_raw_t raw;
	char      *s;

	raw = toml_raw_in(doc_tab, "project-name");
	if (raw && toml_rtos(raw, &s) == 0 && s) {
		cfg->project_name = sdsnew(s);
		free(s);
	} else {
		cfg->project_name = sdsnew(def_name);
	}

	raw = toml_raw_in(doc_tab, "output-dir");
	if (raw && toml_rtos(raw, &s) == 0 && s) {
		cfg->output_dir = sdsnew(s);
		free(s);
	} else {
		cfg->output_dir = sdsnew(def_out);
	}

	raw = toml_raw_in(doc_tab, "input-dirs");
	if (raw && toml_rtos(raw, &s) == 0 && s) {
		cfg->input_dirs = sdsnew(s);
		free(s);
	} else {
		cfg->input_dirs = sdsnew(def_input);
	}

	raw = toml_raw_in(doc_tab, "exclude-patterns");
	if (raw && toml_rtos(raw, &s) == 0 && s) {
		cfg->exclude_patterns = sdsnew(s);
		free(s);
	} else {
		cfg->exclude_patterns = sdsnew("");
	}
}

static void doc_settings_free(doc_settings_t *cfg)
{
	sdsfree(cfg->project_name);
	sdsfree(cfg->output_dir);
	sdsfree(cfg->input_dirs);
	sdsfree(cfg->exclude_patterns);
}

/*
 * Generate a Doxyfile from manifest settings and write it to the project dir.
 */
static i64 doc_generate_doxyfile(manifest_t *m, const sds project_dir)
{
	const char *def_name  = m->package.name ? m->package.name : "Project";
	const char *version   = m->package.version ? m->package.version : "";
	const char *desc      = m->package.description ? m->package.description : "";
	const char *def_input = "src include";

	/* Read [doc] section from Coffee.toml */
	doc_settings_t cfg;
	{
		sds   manifest_path = sdscatprintf(sdsempty(), "%s/Coffee.toml", project_dir);
		FILE *fp            = fopen(manifest_path, "r");
		sdsfree(manifest_path);

		if (fp) {
			char          errbuf[256];
			toml_table_t *conf = toml_parse_file(fp, errbuf, sizeof(errbuf));
			fclose(fp);

			if (conf) {
				toml_table_t *doc_tab = toml_table_in(conf, "doc");
				doc_settings_read(&cfg, doc_tab, def_name, "docs/api", def_input);
				toml_free(conf);
			} else {
				doc_settings_read(&cfg, nullptr, def_name, "docs/api", def_input);
			}
		} else {
			doc_settings_read(&cfg, nullptr, def_name, "docs/api", def_input);
		}
	}

	sds   doxyfile_path = sdscatprintf(sdsempty(), "%s/Doxyfile", project_dir);
	FILE *df            = fopen(doxyfile_path, "w");
	if (df == nullptr) {
		fprintf_safe(stderr, "Error: Could not create Doxyfile at %s\n", doxyfile_path);
		sdsfree(doxyfile_path);
		doc_settings_free(&cfg);
		return 1;
	}

	fprintf_safe(df,
	             "# Doxyfile generated by coffee\n"
	             "# https://doxygen.nl/manual/config.html\n"
	             "\n"
	             "PROJECT_NAME           = \"%s\"\n"
	             "PROJECT_NUMBER         = %s\n"
	             "PROJECT_BRIEF          = \"%s\"\n"
	             "OUTPUT_DIRECTORY       = %s\n"
	             "INPUT                  = %s\n"
	             "RECURSIVE              = YES\n"
	             "GENERATE_LATEX         = NO\n"
	             "GENERATE_HTML          = YES\n"
	             "GENERATE_TREEVIEW      = YES\n"
	             "HAVE_DOT               = YES\n"
	             "DOT_IMAGE_FORMAT       = svg\n"
	             "CALL_GRAPH             = YES\n"
	             "CALLER_GRAPH           = YES\n"
	             "EXTRACT_ALL            = YES\n"
	             "EXTRACT_STATIC         = YES\n"
	             "EXTRACT_PRIVATE        = YES\n"
	             "SOURCE_BROWSER         = YES\n"
	             "INLINE_SOURCES         = NO\n"
	             "SORT_MEMBER_DOCS       = YES\n"
	             "QUIET                  = YES\n"
	             "WARNINGS               = YES\n"
	             "WARN_IF_UNDOCUMENTED   = NO\n"
	             "WARN_FORMAT            = \"$file:$line: $text\"\n",
	             cfg.project_name, version, desc, cfg.output_dir, cfg.input_dirs);

	if (cfg.exclude_patterns && cfg.exclude_patterns[0]) {
		fprintf_safe(df, "EXCLUDE_PATTERNS       = %s\n", cfg.exclude_patterns);
	}

	fclose(df);
	doc_settings_free(&cfg);
	printf("Generated Doxyfile\n");
	sdsfree(doxyfile_path);
	return 0;
}

int64_t handle_doc(options *opts)
{
	bool no_deps = false;
	for (i64 i = 1; i < opts->inputs_num; i++) {
		if (strcmp(opts->inputs[i], "--no-deps") == 0) {
			no_deps = true;
		}
	}

	/* Find and parse manifest */
	char *manifest_path = project_find_manifest(nullptr);
	if (manifest_path == nullptr) {
		fprintf_safe(stderr, "Error: Could not find Coffee.toml\n");
		return 1;
	}

	/* Extract project directory */
	sds   project_dir = sdsnew(manifest_path);
	char *last_slash  = strrchr(project_dir, '/');
	if (last_slash) {
		*last_slash = '\0';
	} else {
		sdsfree(project_dir);
		project_dir = sdsnew(".");
	}

	manifest_t *m = manifest_parse(manifest_path);
	sdsfree(manifest_path);

	if (m == nullptr) {
		fprintf_safe(stderr, "Error: Could not parse Coffee.toml\n");
		sdsfree(project_dir);
		return 1;
	}

	printf("Generating documentation...\n");

	/* Check for existing Doxyfile */
	sds doxyfile_path = sdscatprintf(sdsempty(), "%s/Doxyfile", project_dir);

	if (access(doxyfile_path, F_OK) != 0) {
		/* No Doxyfile — check if [doc] section exists */
		sds   mp = sdscatprintf(sdsempty(), "%s/Coffee.toml", project_dir);
		FILE *fp = fopen(mp, "r");
		sdsfree(mp);

		bool has_doc_section = false;
		if (fp) {
			char          errbuf[256];
			toml_table_t *conf = toml_parse_file(fp, errbuf, sizeof(errbuf));
			fclose(fp);
			if (conf) {
				has_doc_section = (toml_table_in(conf, "doc") != nullptr);
				toml_free(conf);
			}
		}

		if (has_doc_section) {
			/* Generate Doxyfile from manifest */
			if (doc_generate_doxyfile(m, project_dir) != 0) {
				sdsfree(doxyfile_path);
				manifest_free(m);
				sdsfree(project_dir);
				return 1;
			}
		} else {
			printf("No Doxyfile or [doc] section found.\n");
			printf("Tip: Run 'doxygen -g' to generate a default Doxyfile, or add a [doc] section to Coffee.toml\n");
			sdsfree(doxyfile_path);
			manifest_free(m);
			sdsfree(project_dir);
			return 0;
		}
	}

	sdsfree(doxyfile_path);

	/* Run doxygen */
	i64 ret = system("doxygen 2>/dev/null");
	if (ret != 0) {
		fprintf_safe(stderr, "Error: Documentation generation failed. Please ensure 'doxygen' is installed.\n");
		manifest_free(m);
		sdsfree(project_dir);
		return 1;
	}

	printf("Documentation complete.\n");
	manifest_free(m);
	sdsfree(project_dir);
	return 0;
}
