#include "../coffee.h"
#include "../manifest.h"
#include "../project.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <toml.h>
#include <unistd.h>

/*
 * Read a TOML string value from a table, or return default.
 */
static const char *toml_str_def(toml_table_t *tab, const char *key, const char *def)
{
	toml_raw_t raw = toml_raw_in(tab, key);
	if (raw) {
		char *s;
		if (toml_rtos(raw, &s) == 0 && s) {
			static char buf[1024];
			snprintf_safe(buf, sizeof(buf), "%s", s);
			free(s);
			return buf;
		}
	}
	return def;
}

/*
 * Generate a Doxyfile from manifest settings and write it to the project dir.
 */
static i64 doc_generate_doxyfile(manifest_t *m, const sds project_dir)
{
	const char *name    = m->package.name ? m->package.name : "Project";
	const char *version = m->package.version ? m->package.version : "";
	const char *desc    = m->package.description ? m->package.description : "";
	const char *out_dir = "docs/api";
	const char *input   = "src include";
	const char *exclude = "";

	/* Read [doc] section from Coffee.toml */
	sds   manifest_path = sdscatprintf(sdsempty(), "%s/Coffee.toml", project_dir);
	FILE *fp            = fopen(manifest_path, "r");
	sdsfree(manifest_path);

	if (fp) {
		char          errbuf[256];
		toml_table_t *conf = toml_parse_file(fp, errbuf, sizeof(errbuf));
		fclose(fp);

		if (conf) {
			toml_table_t *doc_tab = toml_table_in(conf, "doc");
			if (doc_tab) {
				name    = toml_str_def(doc_tab, "project-name", name);
				out_dir = toml_str_def(doc_tab, "output-dir", "docs/api");
				input   = toml_str_def(doc_tab, "input-dirs", "src include");
				exclude = toml_str_def(doc_tab, "exclude-patterns", "");
			}
			toml_free(conf);
		}
	}

	sds   doxyfile_path = sdscatprintf(sdsempty(), "%s/Doxyfile", project_dir);
	FILE *df            = fopen(doxyfile_path, "w");
	if (df == nullptr) {
		fprintf_safe(stderr, "Error: Could not create Doxyfile at %s\n", doxyfile_path);
		sdsfree(doxyfile_path);
		return 1;
	}

	fprintf_safe(df,
	             "# Doxyfile generated by coffee\n"
	             "# https://doxygen.nl/manual/config.html\n"
	             "\n"
	             "PROJECT_NAME           = \"%s\"\n"
	             "PROJECT_NUMBER         = %s\n"
	             "PROJECT_BRIEF          = \"%s\"\n"
	             "OUTPUT_DIRECTORY       = %s\n"
	             "INPUT                  = %s\n"
	             "RECURSIVE              = YES\n"
	             "GENERATE_LATEX         = NO\n"
	             "GENERATE_HTML          = YES\n"
	             "GENERATE_TREEVIEW      = YES\n"
	             "HAVE_DOT               = YES\n"
	             "DOT_IMAGE_FORMAT       = svg\n"
	             "CALL_GRAPH             = YES\n"
	             "CALLER_GRAPH           = YES\n"
	             "EXTRACT_ALL            = YES\n"
	             "EXTRACT_STATIC         = YES\n"
	             "EXTRACT_PRIVATE        = YES\n"
	             "SOURCE_BROWSER         = YES\n"
	             "INLINE_SOURCES         = NO\n"
	             "SORT_MEMBER_DOCS       = YES\n"
	             "QUIET                  = YES\n"
	             "WARNINGS               = YES\n"
	             "WARN_IF_UNDOCUMENTED   = NO\n"
	             "WARN_FORMAT            = \"$file:$line: $text\"\n",
	             name, version, desc, out_dir, input);

	if (exclude && exclude[0]) {
		fprintf_safe(df, "EXCLUDE_PATTERNS       = %s\n", exclude);
	}

	fclose(df);
	printf("Generated Doxyfile\n");
	sdsfree(doxyfile_path);
	return 0;
}

int64_t handle_doc(options *opts)
{
	bool no_deps = false;
	for (i64 i = 1; i < opts->inputs_num; i++) {
		if (strcmp(opts->inputs[i], "--no-deps") == 0) {
			no_deps = true;
		}
	}

	/* Find and parse manifest */
	char *manifest_path = project_find_manifest(nullptr);
	if (manifest_path == nullptr) {
		fprintf_safe(stderr, "Error: Could not find Coffee.toml\n");
		return 1;
	}

	/* Extract project directory */
	sds   project_dir = sdsnew(manifest_path);
	char *last_slash  = strrchr(project_dir, '/');
	if (last_slash) {
		*last_slash = '\0';
	} else {
		sdsfree(project_dir);
		project_dir = sdsnew(".");
	}

	manifest_t *m = manifest_parse(manifest_path);
	sdsfree(manifest_path);

	if (m == nullptr) {
		fprintf_safe(stderr, "Error: Could not parse Coffee.toml\n");
		sdsfree(project_dir);
		return 1;
	}

	printf("Generating documentation...\n");

	/* Check for existing Doxyfile */
	sds doxyfile_path = sdscatprintf(sdsempty(), "%s/Doxyfile", project_dir);

	if (access(doxyfile_path, F_OK) != 0) {
		/* No Doxyfile — check if [doc] section exists */
		sds   mp = sdscatprintf(sdsempty(), "%s/Coffee.toml", project_dir);
		FILE *fp = fopen(mp, "r");
		sdsfree(mp);

		bool has_doc_section = false;
		if (fp) {
			char          errbuf[256];
			toml_table_t *conf = toml_parse_file(fp, errbuf, sizeof(errbuf));
			fclose(fp);
			if (conf) {
				has_doc_section = (toml_table_in(conf, "doc") != nullptr);
				toml_free(conf);
			}
		}

		if (has_doc_section) {
			/* Generate Doxyfile from manifest */
			if (doc_generate_doxyfile(m, project_dir) != 0) {
				sdsfree(doxyfile_path);
				manifest_free(m);
				sdsfree(project_dir);
				return 1;
			}
		} else {
			printf("No Doxyfile or [doc] section found.\n");
			printf("Tip: Run 'doxygen -g' to generate a default Doxyfile, or add a [doc] section to Coffee.toml\n");
			sdsfree(doxyfile_path);
			manifest_free(m);
			sdsfree(project_dir);
			return 0;
		}
	}

	sdsfree(doxyfile_path);

	/* Run doxygen */
	i64 ret = system("doxygen 2>/dev/null");
	if (ret != 0) {
		fprintf_safe(stderr, "Error: Documentation generation failed. Please ensure 'doxygen' is installed.\n");
		manifest_free(m);
		sdsfree(project_dir);
		return 1;
	}

	printf("Documentation complete.\n");
	manifest_free(m);
	sdsfree(project_dir);
	return 0;
}
