#include "../coffee.h"
#include "../coffee_features.h"
#include "../manifest.h"
#include "../project.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <unistd.h>

int64_t handle_generate_lockfile(options *opts)
{
	char *manifest_path = project_find_manifest(nullptr);

	if (manifest_path == nullptr) {
		fprintf_safe(stderr, "Error: Could not find Coffee.toml\n");
		return 1;
	}

	manifest_t *manifest = manifest_parse(manifest_path);
	free(manifest_path);

	if (manifest == nullptr) {
		fprintf_safe(stderr, "Error: Could not parse Coffee.toml\n");
		return 1;
	}

	char lockfile_path[4'096];
	snprintf_safe(lockfile_path, sizeof(lockfile_path), "Coffee.lock");

	char **features		  = nullptr;
	size_t features_count = 0;
	if (opts->features) {
		features_parse_cli(opts->features, &features, &features_count);
	}

	resolved_features_t *resolved = features_resolve(manifest, (const char **)features, features_count,
													 opts->all_features, opts->no_default_features);

	if (features) {
		for (size_t i = 0; i < features_count; i++) {
			free(features[i]);
		}
		free(features);
	}

	printf("Generating lockfile: %s\n", lockfile_path);

	FILE *fp = fopen(lockfile_path, "w");
	if (fp == nullptr) {
		fprintf_safe(stderr, "Error: Could not create %s\n", lockfile_path);
		if (resolved) {
			features_free(resolved);
		}
		manifest_free(manifest);
		return 1;
	}

	fprintf_safe(fp, "# This file is automatically generated by coffee.\n");
	fprintf_safe(fp, "# It contains the exact versions of all dependencies.\n");
	fprintf_safe(fp, "version = 1\n");

	fprintf_safe(fp, "\n[package]\n");
	if (manifest->package.name) {
		fprintf_safe(fp, "name = \"%s\"\n", manifest->package.name);
	}
	if (manifest->package.version) {
		fprintf_safe(fp, "version = \"%s\"\n", manifest->package.version);
	}

	if (resolved != nullptr && resolved->package_count > 0) {
		fprintf_safe(fp, "\n[features]\n");
		for (size_t i = 0; i < resolved->package_count; i++) {
			if (resolved->package_names[i] != nullptr && resolved->packages[i].count > 0) {
				fprintf_safe(fp, "%s = [", resolved->package_names[i]);
				for (size_t j = 0; j < resolved->packages[i].count; j++) {
					if (j > 0) {
						fprintf_safe(fp, ", ");
					}
					if (resolved->packages[i].names[j]) {
						fprintf_safe(fp, "\"%s\"", resolved->packages[i].names[j]);
					}
				}
				fprintf_safe(fp, "]\n");
			}
		}
	}

	if (manifest->package.dependencies_count > 0) {
		fprintf_safe(fp, "\n[[dependencies]]\n");
		for (size_t i = 0; i < manifest->package.dependencies_count; i++) {
			if (manifest->package.dependencies[i]) {
				fprintf_safe(fp, "%s\n", manifest->package.dependencies[i]);
			}
		}
	}

	fclose(fp);

	if (resolved) {
		features_free(resolved);
	}

	manifest_free(manifest);

	printf("Lockfile generated successfully.\n");
	return 0;
}
