#include "../coffee.h"
#include "../manifest.h"
#include "../project.h"
#include "../registry.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <sys/stat.h>
#include <unistd.h>

int64_t handle_update(options *opts)
{
	char *manifest_path = project_find_manifest(NULL);

	if (!manifest_path) {
		fprintf(stderr, "Error: Could not find Coffee.toml\n");
		return 1;
	}

	manifest_t *m = manifest_parse(manifest_path);
	free(manifest_path);

	if (!m) {
		fprintf(stderr, "Error: Could not parse Coffee.toml\n");
		return 1;
	}

	const char *cache_dir = getenv("HOME");
	if (!cache_dir) {
		cache_dir = "/tmp";
	}

	char deps_dir[4'096];
	snprintf(deps_dir, sizeof(deps_dir), "%s/.coffee/deps", cache_dir);
	mkdir(deps_dir, 0755);

	printf("Updating dependencies...\n");

	char *target = NULL;
	if (opts->inputs_num > 1) {
		target = opts->inputs[1];
	}

	for (size_t i = 0; i < m->package.dependencies_count; i++) {
		const char *entry = m->package.dependencies[i];

		char *name   = strdup(entry);
		char *equals = strchr(name, '=');
		if (equals) {
			*equals	  = '\0';
			char *end = equals - 1;
			while (end > name && *end == ' ') {
				*end = '\0';
				end--;
			}
		}

		if (target && strcmp(name, target) != 0) {
			free(name);
			continue;
		}

		printf("  Updating: %s\n", name);

		char pkg_dir[4'096];
		snprintf(pkg_dir, sizeof(pkg_dir), "%s/%s", deps_dir, name);

		int ret = registry_fetch(name, NULL, pkg_dir);
		if (ret != 0) {
			fprintf(stderr, "Error: Failed to update %s\n", name);
		}

		free(name);
	}

	char lockfile_path[4'096];
	snprintf(lockfile_path, sizeof(lockfile_path), "Coffee.lock");

	FILE *fp = fopen(lockfile_path, "w");
	if (fp) {
		fprintf(fp, "# This file is automatically generated by coffee.\n");
		fprintf(fp, "# It contains the exact versions of all dependencies.\n");
		fprintf(fp, "version = 1\n");

		fprintf(fp, "\n[package]\n");
		if (m->package.name) {
			fprintf(fp, "name = \"%s\"\n", m->package.name);
		}
		if (m->package.version) {
			fprintf(fp, "version = \"%s\"\n", m->package.version);
		}

		if (m->package.dependencies_count > 0) {
			fprintf(fp, "\n[[dependencies]]\n");
			for (size_t i = 0; i < m->package.dependencies_count; i++) {
				if (m->package.dependencies[i]) {
					fprintf(fp, "%s\n", m->package.dependencies[i]);
				}
			}
		}

		fclose(fp);
		printf("Lockfile updated.\n");
	}

	manifest_free(m);
	return 0;
}
