#!/bin/bash
set -euo pipefail

SKELETONS_DIR="${1:-skeletons}"
OUTPUT="${2:-src/skeletons.h}"

mkdir -p "$(dirname "$OUTPUT")"

{
	echo "// Auto-generated by scripts/embed_skeletons.sh. Do not edit."
	echo "#ifndef SKELETONS_H_"
	echo "#define SKELETONS_H_"
	echo ""

	for f in "$SKELETONS_DIR"/*; do
		[[ -f "$f" ]] || continue
		name=$(basename "$f" | sed 's/[^a-zA-Z0-9]/_/g')
		echo "static const char skeleton_${name}[] ="
		awk '{
			gsub(/\\/, "\\\\");
			gsub(/"/, "\\\"");
			printf("    \"%s\\n\"\n", $0);
		}' "$f"
		echo "    ;"
		echo ""
	done

	echo "#endif // SKELETONS_H_"
} > "$OUTPUT"
