/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt -i src/cli.ggo --output-dir=src/ --unamed-opts --strict-hidden

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
# define FIX_UNUSED(X) (void)(X) /* avoid warnings for unused params */
#endif

#include "cmdline.h"

#include <getopt.h>

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: coffee [OPTION]... [FILE]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "A moderm package manager for C";

const char *gengetopt_args_info_help[] = {
	"  -h, --help                    Print help and exit",
	"      --version                 Print version and exit",
	"  -v, --verbose                 Use verbose output (-vv very verbose/build.rs\n                                  "
	"output)  (default=off)",
	"  -q, --quiet                   Do not print cargo log messages  (default=off)",
	"      --color=color             Coloring [possible values: auto, always, never]",
	"      --message-format=message_format\n                                Error format [possible values: human, "
	"json,\n                                  short]",
	"      --manifest-path=manifest_path\n                                Path to Cargo.toml",
	"      --target=target           Build for the target triple",
	"      --debug                   Build with debug symbols  (default=off)",
	"      --release                 Build in release mode  (default=off)",
	"  -j, --jobs=INT                Number of parallel jobs, defaults to # of CPUs",
	"      --bin=bin_name            Build only the specified binary",
	"      --example=example_name    Build only the specified example",
	"      --features=features       Space-separated list of features to activate",
	"      --all-features            Activate all available features  (default=off)",
	"      --no-default-features     Do not activate the `default` feature\n                                  "
	"(default=off)",
	"      --profile=profile         Build with given profile",
	"      --target-dir=target_dir   Directory for all generated artifacts",
	"      --unit-graph              Output build graph in JSON  (default=off)",
	"      --ignore-rust-version     Ignore `rust-version` specification in packages\n                                 "
	" (default=off)",
	"      --timings=timings         Output build timing information",
	"      --future-incompat-report  Outputs a future incompatibility report\n                                  "
	"(default=off)",
	"      --workspace               Build all packages in the workspace\n                                  "
	"(default=off)",
	"      --exclude=exclude         Exclude packages from the build",
	"      --include=include         Include packages in the build",
	"      --lib                     Build only this package's library\n                                  "
	"(default=off)",
	"  -p, --package=pkgid           Package to build",
	"      --locked                  Require Cargo.lock is up to date  (default=off)",
	"      --offline                 Run without accessing the network\n                                  "
	"(default=off)",
	"      --frozen                  Equivalent to both --locked and --offline\n                                  "
	"(default=off)",
	"      --config=config           Override a configuration value",
	"  -Z, --unstable-flags=unstable_flag\n                                Unstable (nightly-only) flags",
	"      --dev                     Add as a development dependency  (default=off)",
	"      --build                   Add as a build dependency  (default=off)",
	"      --optional                Mark dependency as optional  (default=off)",
	"      --no-optional             Mark dependency as required  (default=off)",
	"      --rename=name             Rename the dependency",
	"  -V, --pkg-version=version     Version constraint",
	"      --path=path               Filesystem path to local dependency",
	"      --git=url                 Git repository location",
	"      --branch=branch           Git branch to download",
	"      --tag=tag                 Git tag to download",
	"      --rev=rev                 Git commit reference to download",
	"      --registry=registry       Package registry for this dependency",
	"      --dry-run                 Don't actually write the manifest\n                                  "
	"(default=off)",
	"      --out-dir=path            Output directory for artifacts",
	"      --build-plan              Output the build plan in JSON  (default=off)",
	"      --keep-going              Continue building as much as possible\n                                  "
	"(default=off)",
	"      --bins                    Build all binary targets  (default=off)",
	"      --examples                Build all example targets  (default=off)",
	"      --tests                   Build all test targets  (default=off)",
	"      --benches                 Build all bench targets  (default=off)",
	"      --all-targets             Build all targets  (default=off)",
	"      --no-run                  Don't run the generated binaries  (default=off)",
	"      --no-fail-fast            Run all tests regardless of failure\n                                  "
	"(default=off)",
	0};

typedef enum { ARG_NO, ARG_FLAG, ARG_STRING, ARG_INT, ARG_ENUM } cmdline_parser_arg_type;

static void clear_given(struct gengetopt_args_info *args_info);
static void clear_args(struct gengetopt_args_info *args_info);

static int cmdline_parser_internal(int argc, char **argv, struct gengetopt_args_info *args_info,
								   struct cmdline_parser_params *params, const char *additional_error);

const char *cmdline_parser_toolchain_values[] = {"+stable", "+clang-stable", "+gcc-stable",
												 0}; /*< Possible values for toolchain. */

static char *gengetopt_strdup(const char *s);

static void clear_given(struct gengetopt_args_info *args_info)
{
	args_info->help_given					= 0;
	args_info->version_given				= 0;
	args_info->verbose_given				= 0;
	args_info->quiet_given					= 0;
	args_info->color_given					= 0;
	args_info->message_format_given			= 0;
	args_info->manifest_path_given			= 0;
	args_info->target_given					= 0;
	args_info->debug_given					= 0;
	args_info->release_given				= 0;
	args_info->jobs_given					= 0;
	args_info->bin_given					= 0;
	args_info->example_given				= 0;
	args_info->features_given				= 0;
	args_info->all_features_given			= 0;
	args_info->no_default_features_given	= 0;
	args_info->profile_given				= 0;
	args_info->target_dir_given				= 0;
	args_info->unit_graph_given				= 0;
	args_info->ignore_rust_version_given	= 0;
	args_info->timings_given				= 0;
	args_info->future_incompat_report_given = 0;
	args_info->workspace_given				= 0;
	args_info->exclude_given				= 0;
	args_info->include_given				= 0;
	args_info->lib_given					= 0;
	args_info->package_given				= 0;
	args_info->locked_given					= 0;
	args_info->offline_given				= 0;
	args_info->frozen_given					= 0;
	args_info->config_given					= 0;
	args_info->unstable_flags_given			= 0;
	args_info->dev_given					= 0;
	args_info->build_given					= 0;
	args_info->optional_given				= 0;
	args_info->no_optional_given			= 0;
	args_info->rename_given					= 0;
	args_info->pkg_version_given			= 0;
	args_info->path_given					= 0;
	args_info->git_given					= 0;
	args_info->branch_given					= 0;
	args_info->tag_given					= 0;
	args_info->rev_given					= 0;
	args_info->registry_given				= 0;
	args_info->dry_run_given				= 0;
	args_info->out_dir_given				= 0;
	args_info->build_plan_given				= 0;
	args_info->keep_going_given				= 0;
	args_info->bins_given					= 0;
	args_info->examples_given				= 0;
	args_info->tests_given					= 0;
	args_info->benches_given				= 0;
	args_info->all_targets_given			= 0;
	args_info->no_run_given					= 0;
	args_info->no_fail_fast_given			= 0;
	args_info->toolchain_given				= 0;
	args_info->command_given				= 0;
}

static void clear_args(struct gengetopt_args_info *args_info)
{
	FIX_UNUSED(args_info);
	args_info->verbose_flag				   = 0;
	args_info->quiet_flag				   = 0;
	args_info->color_arg				   = NULL;
	args_info->color_orig				   = NULL;
	args_info->message_format_arg		   = NULL;
	args_info->message_format_orig		   = NULL;
	args_info->manifest_path_arg		   = NULL;
	args_info->manifest_path_orig		   = NULL;
	args_info->target_arg				   = NULL;
	args_info->target_orig				   = NULL;
	args_info->debug_flag				   = 0;
	args_info->release_flag				   = 0;
	args_info->jobs_orig				   = NULL;
	args_info->bin_arg					   = NULL;
	args_info->bin_orig					   = NULL;
	args_info->example_arg				   = NULL;
	args_info->example_orig				   = NULL;
	args_info->features_arg				   = NULL;
	args_info->features_orig			   = NULL;
	args_info->all_features_flag		   = 0;
	args_info->no_default_features_flag	   = 0;
	args_info->profile_arg				   = NULL;
	args_info->profile_orig				   = NULL;
	args_info->target_dir_arg			   = NULL;
	args_info->target_dir_orig			   = NULL;
	args_info->unit_graph_flag			   = 0;
	args_info->ignore_rust_version_flag	   = 0;
	args_info->timings_arg				   = NULL;
	args_info->timings_orig				   = NULL;
	args_info->future_incompat_report_flag = 0;
	args_info->workspace_flag			   = 0;
	args_info->exclude_arg				   = NULL;
	args_info->exclude_orig				   = NULL;
	args_info->include_arg				   = NULL;
	args_info->include_orig				   = NULL;
	args_info->lib_flag					   = 0;
	args_info->package_arg				   = NULL;
	args_info->package_orig				   = NULL;
	args_info->locked_flag				   = 0;
	args_info->offline_flag				   = 0;
	args_info->frozen_flag				   = 0;
	args_info->config_arg				   = NULL;
	args_info->config_orig				   = NULL;
	args_info->unstable_flags_arg		   = NULL;
	args_info->unstable_flags_orig		   = NULL;
	args_info->dev_flag					   = 0;
	args_info->build_flag				   = 0;
	args_info->optional_flag			   = 0;
	args_info->no_optional_flag			   = 0;
	args_info->rename_arg				   = NULL;
	args_info->rename_orig				   = NULL;
	args_info->pkg_version_arg			   = NULL;
	args_info->pkg_version_orig			   = NULL;
	args_info->path_arg					   = NULL;
	args_info->path_orig				   = NULL;
	args_info->git_arg					   = NULL;
	args_info->git_orig					   = NULL;
	args_info->branch_arg				   = NULL;
	args_info->branch_orig				   = NULL;
	args_info->tag_arg					   = NULL;
	args_info->tag_orig					   = NULL;
	args_info->rev_arg					   = NULL;
	args_info->rev_orig					   = NULL;
	args_info->registry_arg				   = NULL;
	args_info->registry_orig			   = NULL;
	args_info->dry_run_flag				   = 0;
	args_info->out_dir_arg				   = NULL;
	args_info->out_dir_orig				   = NULL;
	args_info->build_plan_flag			   = 0;
	args_info->keep_going_flag			   = 0;
	args_info->bins_flag				   = 0;
	args_info->examples_flag			   = 0;
	args_info->tests_flag				   = 0;
	args_info->benches_flag				   = 0;
	args_info->all_targets_flag			   = 0;
	args_info->no_run_flag				   = 0;
	args_info->no_fail_fast_flag		   = 0;
	args_info->toolchain_arg			   = toolchain__NULL;
	args_info->toolchain_orig			   = NULL;
	args_info->command_arg				   = NULL;
	args_info->command_orig				   = NULL;
}

static void init_args_info(struct gengetopt_args_info *args_info)
{

	args_info->help_help				   = gengetopt_args_info_help[0];
	args_info->version_help				   = gengetopt_args_info_help[1];
	args_info->verbose_help				   = gengetopt_args_info_help[2];
	args_info->quiet_help				   = gengetopt_args_info_help[3];
	args_info->color_help				   = gengetopt_args_info_help[4];
	args_info->message_format_help		   = gengetopt_args_info_help[5];
	args_info->manifest_path_help		   = gengetopt_args_info_help[6];
	args_info->target_help				   = gengetopt_args_info_help[7];
	args_info->debug_help				   = gengetopt_args_info_help[8];
	args_info->release_help				   = gengetopt_args_info_help[9];
	args_info->jobs_help				   = gengetopt_args_info_help[10];
	args_info->bin_help					   = gengetopt_args_info_help[11];
	args_info->example_help				   = gengetopt_args_info_help[12];
	args_info->features_help			   = gengetopt_args_info_help[13];
	args_info->all_features_help		   = gengetopt_args_info_help[14];
	args_info->no_default_features_help	   = gengetopt_args_info_help[15];
	args_info->profile_help				   = gengetopt_args_info_help[16];
	args_info->target_dir_help			   = gengetopt_args_info_help[17];
	args_info->unit_graph_help			   = gengetopt_args_info_help[18];
	args_info->ignore_rust_version_help	   = gengetopt_args_info_help[19];
	args_info->timings_help				   = gengetopt_args_info_help[20];
	args_info->future_incompat_report_help = gengetopt_args_info_help[21];
	args_info->workspace_help			   = gengetopt_args_info_help[22];
	args_info->exclude_help				   = gengetopt_args_info_help[23];
	args_info->include_help				   = gengetopt_args_info_help[24];
	args_info->lib_help					   = gengetopt_args_info_help[25];
	args_info->package_help				   = gengetopt_args_info_help[26];
	args_info->locked_help				   = gengetopt_args_info_help[27];
	args_info->offline_help				   = gengetopt_args_info_help[28];
	args_info->frozen_help				   = gengetopt_args_info_help[29];
	args_info->config_help				   = gengetopt_args_info_help[30];
	args_info->unstable_flags_help		   = gengetopt_args_info_help[31];
	args_info->dev_help					   = gengetopt_args_info_help[32];
	args_info->build_help				   = gengetopt_args_info_help[33];
	args_info->optional_help			   = gengetopt_args_info_help[34];
	args_info->no_optional_help			   = gengetopt_args_info_help[35];
	args_info->rename_help				   = gengetopt_args_info_help[36];
	args_info->pkg_version_help			   = gengetopt_args_info_help[37];
	args_info->path_help				   = gengetopt_args_info_help[38];
	args_info->git_help					   = gengetopt_args_info_help[39];
	args_info->branch_help				   = gengetopt_args_info_help[40];
	args_info->tag_help					   = gengetopt_args_info_help[41];
	args_info->rev_help					   = gengetopt_args_info_help[42];
	args_info->registry_help			   = gengetopt_args_info_help[43];
	args_info->dry_run_help				   = gengetopt_args_info_help[44];
	args_info->out_dir_help				   = gengetopt_args_info_help[45];
	args_info->build_plan_help			   = gengetopt_args_info_help[46];
	args_info->keep_going_help			   = gengetopt_args_info_help[47];
	args_info->bins_help				   = gengetopt_args_info_help[48];
	args_info->examples_help			   = gengetopt_args_info_help[49];
	args_info->tests_help				   = gengetopt_args_info_help[50];
	args_info->benches_help				   = gengetopt_args_info_help[51];
	args_info->all_targets_help			   = gengetopt_args_info_help[52];
	args_info->no_run_help				   = gengetopt_args_info_help[53];
	args_info->no_fail_fast_help		   = gengetopt_args_info_help[54];
	args_info->toolchain_help			   = gengetopt_args_info_help[55];
	args_info->command_help				   = gengetopt_args_info_help[56];
}

void cmdline_parser_print_version(void)
{
	printf("%s %s\n", (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
		   CMDLINE_PARSER_VERSION);

	if (strlen(gengetopt_args_info_versiontext) > 0) {
		printf("\n%s\n", gengetopt_args_info_versiontext);
	}
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage   = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void cmdline_parser_print_help(void)
{
	int i = 0;
	print_help_common();
	while (gengetopt_args_info_help[i]) {
		printf("%s\n", gengetopt_args_info_help[i++]);
	}
}

void cmdline_parser_init(struct gengetopt_args_info *args_info)
{
	clear_given(args_info);
	clear_args(args_info);
	init_args_info(args_info);

	args_info->inputs	  = 0;
	args_info->inputs_num = 0;
}

void cmdline_parser_params_init(struct cmdline_parser_params *params)
{
	if (params) {
		params->override		= 0;
		params->initialize		= 1;
		params->check_required	= 1;
		params->check_ambiguity = 0;
		params->print_errors	= 1;
	}
}

struct cmdline_parser_params *cmdline_parser_params_create(void)
{
	struct cmdline_parser_params *params = (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
	cmdline_parser_params_init(params);
	return params;
}

static void free_string_field(char **s)
{
	if (*s) {
		free(*s);
		*s = 0;
	}
}

static void cmdline_parser_release(struct gengetopt_args_info *args_info)
{
	unsigned int i;
	free_string_field(&(args_info->color_arg));
	free_string_field(&(args_info->color_orig));
	free_string_field(&(args_info->message_format_arg));
	free_string_field(&(args_info->message_format_orig));
	free_string_field(&(args_info->manifest_path_arg));
	free_string_field(&(args_info->manifest_path_orig));
	free_string_field(&(args_info->target_arg));
	free_string_field(&(args_info->target_orig));
	free_string_field(&(args_info->jobs_orig));
	free_string_field(&(args_info->bin_arg));
	free_string_field(&(args_info->bin_orig));
	free_string_field(&(args_info->example_arg));
	free_string_field(&(args_info->example_orig));
	free_string_field(&(args_info->features_arg));
	free_string_field(&(args_info->features_orig));
	free_string_field(&(args_info->profile_arg));
	free_string_field(&(args_info->profile_orig));
	free_string_field(&(args_info->target_dir_arg));
	free_string_field(&(args_info->target_dir_orig));
	free_string_field(&(args_info->timings_arg));
	free_string_field(&(args_info->timings_orig));
	free_string_field(&(args_info->exclude_arg));
	free_string_field(&(args_info->exclude_orig));
	free_string_field(&(args_info->include_arg));
	free_string_field(&(args_info->include_orig));
	free_string_field(&(args_info->package_arg));
	free_string_field(&(args_info->package_orig));
	free_string_field(&(args_info->config_arg));
	free_string_field(&(args_info->config_orig));
	free_string_field(&(args_info->unstable_flags_arg));
	free_string_field(&(args_info->unstable_flags_orig));
	free_string_field(&(args_info->rename_arg));
	free_string_field(&(args_info->rename_orig));
	free_string_field(&(args_info->pkg_version_arg));
	free_string_field(&(args_info->pkg_version_orig));
	free_string_field(&(args_info->path_arg));
	free_string_field(&(args_info->path_orig));
	free_string_field(&(args_info->git_arg));
	free_string_field(&(args_info->git_orig));
	free_string_field(&(args_info->branch_arg));
	free_string_field(&(args_info->branch_orig));
	free_string_field(&(args_info->tag_arg));
	free_string_field(&(args_info->tag_orig));
	free_string_field(&(args_info->rev_arg));
	free_string_field(&(args_info->rev_orig));
	free_string_field(&(args_info->registry_arg));
	free_string_field(&(args_info->registry_orig));
	free_string_field(&(args_info->out_dir_arg));
	free_string_field(&(args_info->out_dir_orig));
	free_string_field(&(args_info->toolchain_orig));
	free_string_field(&(args_info->command_arg));
	free_string_field(&(args_info->command_orig));

	for (i = 0; i < args_info->inputs_num; ++i) {
		free(args_info->inputs[i]);
	}

	if (args_info->inputs_num) {
		free(args_info->inputs);
	}

	clear_given(args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int check_possible_values(const char *val, const char *values[])
{
	int	   i, found, last;
	size_t len;

	if (!val) {	   /* otherwise strlen() crashes below */
		return -1; /* -1 means no argument for the option */
	}

	found = last = 0;

	for (i = 0, len = strlen(val); values[i]; ++i) {
		if (strncmp(val, values[i], len) == 0) {
			++found;
			last = i;
			if (strlen(values[i]) == len) {
				return i; /* exact macth no need to check more */
			}
		}
	}

	if (found == 1) { /* one match: OK */
		return last;
	}

	return (found ? -2 : -1); /* return many values or none matched */
}

static void write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
	int found = -1;
	if (arg) {
		if (values) {
			found = check_possible_values(arg, values);
		}
		if (found >= 0) {
			fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
		} else {
			fprintf(outfile, "%s=\"%s\"\n", opt, arg);
		}
	} else {
		fprintf(outfile, "%s\n", opt);
	}
}

int cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
	int i = 0;

	if (!outfile) {
		fprintf(stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
		return EXIT_FAILURE;
	}

	if (args_info->help_given) {
		write_into_file(outfile, "help", 0, 0);
	}
	if (args_info->version_given) {
		write_into_file(outfile, "version", 0, 0);
	}
	if (args_info->verbose_given) {
		write_into_file(outfile, "verbose", 0, 0);
	}
	if (args_info->quiet_given) {
		write_into_file(outfile, "quiet", 0, 0);
	}
	if (args_info->color_given) {
		write_into_file(outfile, "color", args_info->color_orig, 0);
	}
	if (args_info->message_format_given) {
		write_into_file(outfile, "message-format", args_info->message_format_orig, 0);
	}
	if (args_info->manifest_path_given) {
		write_into_file(outfile, "manifest-path", args_info->manifest_path_orig, 0);
	}
	if (args_info->target_given) {
		write_into_file(outfile, "target", args_info->target_orig, 0);
	}
	if (args_info->debug_given) {
		write_into_file(outfile, "debug", 0, 0);
	}
	if (args_info->release_given) {
		write_into_file(outfile, "release", 0, 0);
	}
	if (args_info->jobs_given) {
		write_into_file(outfile, "jobs", args_info->jobs_orig, 0);
	}
	if (args_info->bin_given) {
		write_into_file(outfile, "bin", args_info->bin_orig, 0);
	}
	if (args_info->example_given) {
		write_into_file(outfile, "example", args_info->example_orig, 0);
	}
	if (args_info->features_given) {
		write_into_file(outfile, "features", args_info->features_orig, 0);
	}
	if (args_info->all_features_given) {
		write_into_file(outfile, "all-features", 0, 0);
	}
	if (args_info->no_default_features_given) {
		write_into_file(outfile, "no-default-features", 0, 0);
	}
	if (args_info->profile_given) {
		write_into_file(outfile, "profile", args_info->profile_orig, 0);
	}
	if (args_info->target_dir_given) {
		write_into_file(outfile, "target-dir", args_info->target_dir_orig, 0);
	}
	if (args_info->unit_graph_given) {
		write_into_file(outfile, "unit-graph", 0, 0);
	}
	if (args_info->ignore_rust_version_given) {
		write_into_file(outfile, "ignore-rust-version", 0, 0);
	}
	if (args_info->timings_given) {
		write_into_file(outfile, "timings", args_info->timings_orig, 0);
	}
	if (args_info->future_incompat_report_given) {
		write_into_file(outfile, "future-incompat-report", 0, 0);
	}
	if (args_info->workspace_given) {
		write_into_file(outfile, "workspace", 0, 0);
	}
	if (args_info->exclude_given) {
		write_into_file(outfile, "exclude", args_info->exclude_orig, 0);
	}
	if (args_info->include_given) {
		write_into_file(outfile, "include", args_info->include_orig, 0);
	}
	if (args_info->lib_given) {
		write_into_file(outfile, "lib", 0, 0);
	}
	if (args_info->package_given) {
		write_into_file(outfile, "package", args_info->package_orig, 0);
	}
	if (args_info->locked_given) {
		write_into_file(outfile, "locked", 0, 0);
	}
	if (args_info->offline_given) {
		write_into_file(outfile, "offline", 0, 0);
	}
	if (args_info->frozen_given) {
		write_into_file(outfile, "frozen", 0, 0);
	}
	if (args_info->config_given) {
		write_into_file(outfile, "config", args_info->config_orig, 0);
	}
	if (args_info->unstable_flags_given) {
		write_into_file(outfile, "unstable-flags", args_info->unstable_flags_orig, 0);
	}
	if (args_info->dev_given) {
		write_into_file(outfile, "dev", 0, 0);
	}
	if (args_info->build_given) {
		write_into_file(outfile, "build", 0, 0);
	}
	if (args_info->optional_given) {
		write_into_file(outfile, "optional", 0, 0);
	}
	if (args_info->no_optional_given) {
		write_into_file(outfile, "no-optional", 0, 0);
	}
	if (args_info->rename_given) {
		write_into_file(outfile, "rename", args_info->rename_orig, 0);
	}
	if (args_info->pkg_version_given) {
		write_into_file(outfile, "pkg-version", args_info->pkg_version_orig, 0);
	}
	if (args_info->path_given) {
		write_into_file(outfile, "path", args_info->path_orig, 0);
	}
	if (args_info->git_given) {
		write_into_file(outfile, "git", args_info->git_orig, 0);
	}
	if (args_info->branch_given) {
		write_into_file(outfile, "branch", args_info->branch_orig, 0);
	}
	if (args_info->tag_given) {
		write_into_file(outfile, "tag", args_info->tag_orig, 0);
	}
	if (args_info->rev_given) {
		write_into_file(outfile, "rev", args_info->rev_orig, 0);
	}
	if (args_info->registry_given) {
		write_into_file(outfile, "registry", args_info->registry_orig, 0);
	}
	if (args_info->dry_run_given) {
		write_into_file(outfile, "dry-run", 0, 0);
	}
	if (args_info->out_dir_given) {
		write_into_file(outfile, "out-dir", args_info->out_dir_orig, 0);
	}
	if (args_info->build_plan_given) {
		write_into_file(outfile, "build-plan", 0, 0);
	}
	if (args_info->keep_going_given) {
		write_into_file(outfile, "keep-going", 0, 0);
	}
	if (args_info->bins_given) {
		write_into_file(outfile, "bins", 0, 0);
	}
	if (args_info->examples_given) {
		write_into_file(outfile, "examples", 0, 0);
	}
	if (args_info->tests_given) {
		write_into_file(outfile, "tests", 0, 0);
	}
	if (args_info->benches_given) {
		write_into_file(outfile, "benches", 0, 0);
	}
	if (args_info->all_targets_given) {
		write_into_file(outfile, "all-targets", 0, 0);
	}
	if (args_info->no_run_given) {
		write_into_file(outfile, "no-run", 0, 0);
	}
	if (args_info->no_fail_fast_given) {
		write_into_file(outfile, "no-fail-fast", 0, 0);
	}
	if (args_info->toolchain_given) {
		write_into_file(outfile, "toolchain", args_info->toolchain_orig, cmdline_parser_toolchain_values);
	}
	if (args_info->command_given) {
		write_into_file(outfile, "command", args_info->command_orig, 0);
	}

	i = EXIT_SUCCESS;
	return i;
}

int cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
	FILE *outfile;
	int	  i = 0;

	outfile = fopen(filename, "w");

	if (!outfile) {
		fprintf(stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
		return EXIT_FAILURE;
	}

	i = cmdline_parser_dump(outfile, args_info);
	fclose(outfile);

	return i;
}

void cmdline_parser_free(struct gengetopt_args_info *args_info)
{
	cmdline_parser_release(args_info);
}

/** @brief replacement of strdup, which is not standard */
char *gengetopt_strdup(const char *s)
{
	char *result = 0;
	if (!s) {
		return result;
	}

	result = (char *)malloc(strlen(s) + 1);
	if (result == (char *)0) {
		return (char *)0;
	}
	strcpy(result, s);
	return result;
}

int cmdline_parser(int argc, char **argv, struct gengetopt_args_info *args_info)
{
	return cmdline_parser2(argc, argv, args_info, 0, 1, 1);
}

int cmdline_parser_ext(int argc, char **argv, struct gengetopt_args_info *args_info,
					   struct cmdline_parser_params *params)
{
	int result;
	result = cmdline_parser_internal(argc, argv, args_info, params, 0);

	if (result == EXIT_FAILURE) {
		cmdline_parser_free(args_info);
		exit(EXIT_FAILURE);
	}

	return result;
}

int cmdline_parser2(int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize,
					int check_required)
{
	int							 result;
	struct cmdline_parser_params params;

	params.override		   = override;
	params.initialize	   = initialize;
	params.check_required  = check_required;
	params.check_ambiguity = 0;
	params.print_errors	   = 1;

	result = cmdline_parser_internal(argc, argv, args_info, &params, 0);

	if (result == EXIT_FAILURE) {
		cmdline_parser_free(args_info);
		exit(EXIT_FAILURE);
	}

	return result;
}

int cmdline_parser_required(struct gengetopt_args_info *args_info, const char *prog_name)
{
	FIX_UNUSED(args_info);
	FIX_UNUSED(prog_name);
	return EXIT_SUCCESS;
}

static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static int update_arg(void *field, char **orig_field, unsigned int *field_given, unsigned int *prev_given, char *value,
					  const char *possible_values[], const char *default_value, cmdline_parser_arg_type arg_type,
					  int check_ambiguity, int override, int no_free, int multiple_option, const char *long_opt,
					  char short_opt, const char *additional_error)
{
	char	   *stop_char = 0;
	const char *val		  = value;
	int			found;
	char	  **string_field;
	FIX_UNUSED(field);

	stop_char = 0;
	found	  = 0;

	if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given))) {
		if (short_opt != '-') {
			fprintf(stderr, "%s: `--%s' (`-%c') option given more than once%s\n", package_name, long_opt, short_opt,
					(additional_error ? additional_error : ""));
		} else {
			fprintf(stderr, "%s: `--%s' option given more than once%s\n", package_name, long_opt,
					(additional_error ? additional_error : ""));
		}
		return 1; /* failure */
	}

	if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0) {
		if (short_opt != '-') {
			fprintf(stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", package_name,
					(found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
					(additional_error ? additional_error : ""));
		} else {
			fprintf(stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", package_name,
					(found == -2) ? "ambiguous" : "invalid", value, long_opt,
					(additional_error ? additional_error : ""));
		}
		return 1; /* failure */
	}

	if (field_given && *field_given && !override) {
		return 0;
	}
	if (prev_given) {
		(*prev_given)++;
	}
	if (field_given) {
		(*field_given)++;
	}
	if (possible_values) {
		val = possible_values[found];
	}

	switch (arg_type) {
	case ARG_FLAG:
		*((int *)field) = !*((int *)field);
		break;
	case ARG_INT:
		if (val) {
			*((int *)field) = strtol(val, &stop_char, 0);
		}
		break;
	case ARG_ENUM:
		if (val) {
			*((int *)field) = found;
		}
		break;
	case ARG_STRING:
		if (val) {
			string_field = (char **)field;
			if (!no_free && *string_field) {
				free(*string_field); /* free previous string */
			}
			*string_field = gengetopt_strdup(val);
		}
		break;
	default:
		break;
	};

	/* check numeric conversion */
	switch (arg_type) {
	case ARG_INT:
		if (val && !(stop_char && *stop_char == '\0')) {
			fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
			return 1; /* failure */
		}
		break;
	default:;
	};

	/* store the original value */
	switch (arg_type) {
	case ARG_NO:
	case ARG_FLAG:
		break;
	default:
		if (value && orig_field) {
			if (no_free) {
				*orig_field = value;
			} else {
				if (*orig_field) {
					free(*orig_field); /* free previous string */
				}
				*orig_field = gengetopt_strdup(value);
			}
		}
	};

	return 0; /* OK */
}

int cmdline_parser_internal(int argc, char **argv, struct gengetopt_args_info *args_info,
							struct cmdline_parser_params *params, const char *additional_error)
{
	int c; /* Character of the parsed option.  */

	int						   error_occurred = 0;
	struct gengetopt_args_info local_args_info;

	int override;
	int initialize;
	int check_required;
	int check_ambiguity;

	package_name = argv[0];

	/* TODO: Why is this here? It is not used anywhere. */
	override = params->override;
	FIX_UNUSED(override);

	initialize	   = params->initialize;
	check_required = params->check_required;

	/* TODO: Why is this here? It is not used anywhere. */
	check_ambiguity = params->check_ambiguity;
	FIX_UNUSED(check_ambiguity);

	if (initialize) {
		cmdline_parser_init(args_info);
	}

	cmdline_parser_init(&local_args_info);

	optarg = 0;
	optind = 0;
	opterr = params->print_errors;
	optopt = '?';

	while (1) {
		int option_index = 0;

		static struct option long_options[] = {{"help", 0, NULL, 'h'},		  {"version", 0, NULL, 0},
											   {"verbose", 0, NULL, 'v'},	  {"quiet", 0, NULL, 'q'},
											   {"color", 1, NULL, 0},		  {"message-format", 1, NULL, 0},
											   {"manifest-path", 1, NULL, 0}, {"target", 1, NULL, 0},
											   {"debug", 0, NULL, 0},		  {"release", 0, NULL, 0},
											   {"jobs", 1, NULL, 'j'},		  {"bin", 1, NULL, 0},
											   {"example", 1, NULL, 0},		  {"features", 1, NULL, 0},
											   {"all-features", 0, NULL, 0},  {"no-default-features", 0, NULL, 0},
											   {"profile", 1, NULL, 0},		  {"target-dir", 1, NULL, 0},
											   {"unit-graph", 0, NULL, 0},	  {"ignore-rust-version", 0, NULL, 0},
											   {"timings", 1, NULL, 0},		  {"future-incompat-report", 0, NULL, 0},
											   {"workspace", 0, NULL, 0},	  {"exclude", 1, NULL, 0},
											   {"include", 1, NULL, 0},		  {"lib", 0, NULL, 0},
											   {"package", 1, NULL, 'p'},	  {"locked", 0, NULL, 0},
											   {"offline", 0, NULL, 0},		  {"frozen", 0, NULL, 0},
											   {"config", 1, NULL, 0},		  {"unstable-flags", 1, NULL, 'Z'},
											   {"dev", 0, NULL, 0},			  {"build", 0, NULL, 0},
											   {"optional", 0, NULL, 0},	  {"no-optional", 0, NULL, 0},
											   {"rename", 1, NULL, 0},		  {"pkg-version", 1, NULL, 'V'},
											   {"path", 1, NULL, 0},		  {"git", 1, NULL, 0},
											   {"branch", 1, NULL, 0},		  {"tag", 1, NULL, 0},
											   {"rev", 1, NULL, 0},			  {"registry", 1, NULL, 0},
											   {"dry-run", 0, NULL, 0},		  {"out-dir", 1, NULL, 0},
											   {"build-plan", 0, NULL, 0},	  {"keep-going", 0, NULL, 0},
											   {"bins", 0, NULL, 0},		  {"examples", 0, NULL, 0},
											   {"tests", 0, NULL, 0},		  {"benches", 0, NULL, 0},
											   {"all-targets", 0, NULL, 0},	  {"no-run", 0, NULL, 0},
											   {"no-fail-fast", 0, NULL, 0},  {"toolchain", 1, NULL, 0},
											   {"command", 1, NULL, 0},		  {0, 0, 0, 0}};

		c = getopt_long(argc, argv, "hvqj:p:Z:V:", long_options, &option_index);

		if (c == -1) {
			break; /* Exit from `while (1)' loop.  */
		}

		switch (c) {
		case 'h': /* Print help and exit.  */
			cmdline_parser_print_help();
			cmdline_parser_free(&local_args_info);
			exit(EXIT_SUCCESS);

		case 'v': /* Use verbose output (-vv very verbose/build.rs output).  */

			if (update_arg((void *)&(args_info->verbose_flag), 0, &(args_info->verbose_given),
						   &(local_args_info.verbose_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0,
						   "verbose", 'v', additional_error)) {
				goto failure;
			}

			break;
		case 'q': /* Do not print cargo log messages.  */

			if (update_arg((void *)&(args_info->quiet_flag), 0, &(args_info->quiet_given),
						   &(local_args_info.quiet_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0,
						   "quiet", 'q', additional_error)) {
				goto failure;
			}

			break;
		case 'j': /* Number of parallel jobs, defaults to # of CPUs.  */

			if (update_arg((void *)&(args_info->jobs_arg), &(args_info->jobs_orig), &(args_info->jobs_given),
						   &(local_args_info.jobs_given), optarg, 0, 0, ARG_INT, check_ambiguity, override, 0, 0,
						   "jobs", 'j', additional_error)) {
				goto failure;
			}

			break;
		case 'p': /* Package to build.  */

			if (update_arg((void *)&(args_info->package_arg), &(args_info->package_orig), &(args_info->package_given),
						   &(local_args_info.package_given), optarg, 0, 0, ARG_STRING, check_ambiguity, override, 0, 0,
						   "package", 'p', additional_error)) {
				goto failure;
			}

			break;
		case 'Z': /* Unstable (nightly-only) flags.  */

			if (update_arg((void *)&(args_info->unstable_flags_arg), &(args_info->unstable_flags_orig),
						   &(args_info->unstable_flags_given), &(local_args_info.unstable_flags_given), optarg, 0, 0,
						   ARG_STRING, check_ambiguity, override, 0, 0, "unstable-flags", 'Z', additional_error)) {
				goto failure;
			}

			break;
		case 'V': /* Version constraint.  */

			if (update_arg((void *)&(args_info->pkg_version_arg), &(args_info->pkg_version_orig),
						   &(args_info->pkg_version_given), &(local_args_info.pkg_version_given), optarg, 0, 0,
						   ARG_STRING, check_ambiguity, override, 0, 0, "pkg-version", 'V', additional_error)) {
				goto failure;
			}

			break;

		case 0: /* Long option with no short option */
			if (strcmp(long_options[option_index].name, "version") == 0) {
				cmdline_parser_print_version();
				cmdline_parser_free(&local_args_info);
				exit(EXIT_SUCCESS);
			}

			/* Coloring [possible values: auto, always, never].  */
			if (strcmp(long_options[option_index].name, "color") == 0) {

				if (update_arg((void *)&(args_info->color_arg), &(args_info->color_orig), &(args_info->color_given),
							   &(local_args_info.color_given), optarg, 0, 0, ARG_STRING, check_ambiguity, override, 0,
							   0, "color", '-', additional_error)) {
					goto failure;
				}

			}
			/* Error format [possible values: human, json, short].  */
			else if (strcmp(long_options[option_index].name, "message-format") == 0) {

				if (update_arg((void *)&(args_info->message_format_arg), &(args_info->message_format_orig),
							   &(args_info->message_format_given), &(local_args_info.message_format_given), optarg, 0,
							   0, ARG_STRING, check_ambiguity, override, 0, 0, "message-format", '-',
							   additional_error)) {
					goto failure;
				}

			}
			/* Path to Cargo.toml.  */
			else if (strcmp(long_options[option_index].name, "manifest-path") == 0) {

				if (update_arg((void *)&(args_info->manifest_path_arg), &(args_info->manifest_path_orig),
							   &(args_info->manifest_path_given), &(local_args_info.manifest_path_given), optarg, 0, 0,
							   ARG_STRING, check_ambiguity, override, 0, 0, "manifest-path", '-', additional_error)) {
					goto failure;
				}

			}
			/* Build for the target triple.  */
			else if (strcmp(long_options[option_index].name, "target") == 0) {

				if (update_arg((void *)&(args_info->target_arg), &(args_info->target_orig), &(args_info->target_given),
							   &(local_args_info.target_given), optarg, 0, 0, ARG_STRING, check_ambiguity, override, 0,
							   0, "target", '-', additional_error)) {
					goto failure;
				}

			}
			/* Build with debug symbols.  */
			else if (strcmp(long_options[option_index].name, "debug") == 0) {

				if (update_arg((void *)&(args_info->debug_flag), 0, &(args_info->debug_given),
							   &(local_args_info.debug_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0,
							   "debug", '-', additional_error)) {
					goto failure;
				}

			}
			/* Build in release mode.  */
			else if (strcmp(long_options[option_index].name, "release") == 0) {

				if (update_arg((void *)&(args_info->release_flag), 0, &(args_info->release_given),
							   &(local_args_info.release_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1,
							   0, "release", '-', additional_error)) {
					goto failure;
				}

			}
			/* Build only the specified binary.  */
			else if (strcmp(long_options[option_index].name, "bin") == 0) {

				if (update_arg((void *)&(args_info->bin_arg), &(args_info->bin_orig), &(args_info->bin_given),
							   &(local_args_info.bin_given), optarg, 0, 0, ARG_STRING, check_ambiguity, override, 0, 0,
							   "bin", '-', additional_error)) {
					goto failure;
				}

			}
			/* Build only the specified example.  */
			else if (strcmp(long_options[option_index].name, "example") == 0) {

				if (update_arg((void *)&(args_info->example_arg), &(args_info->example_orig),
							   &(args_info->example_given), &(local_args_info.example_given), optarg, 0, 0, ARG_STRING,
							   check_ambiguity, override, 0, 0, "example", '-', additional_error)) {
					goto failure;
				}

			}
			/* Space-separated list of features to activate.  */
			else if (strcmp(long_options[option_index].name, "features") == 0) {

				if (update_arg((void *)&(args_info->features_arg), &(args_info->features_orig),
							   &(args_info->features_given), &(local_args_info.features_given), optarg, 0, 0,
							   ARG_STRING, check_ambiguity, override, 0, 0, "features", '-', additional_error)) {
					goto failure;
				}

			}
			/* Activate all available features.  */
			else if (strcmp(long_options[option_index].name, "all-features") == 0) {

				if (update_arg((void *)&(args_info->all_features_flag), 0, &(args_info->all_features_given),
							   &(local_args_info.all_features_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override,
							   1, 0, "all-features", '-', additional_error)) {
					goto failure;
				}

			}
			/* Do not activate the `default` feature.  */
			else if (strcmp(long_options[option_index].name, "no-default-features") == 0) {

				if (update_arg((void *)&(args_info->no_default_features_flag), 0,
							   &(args_info->no_default_features_given), &(local_args_info.no_default_features_given),
							   optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0, "no-default-features", '-',
							   additional_error)) {
					goto failure;
				}

			}
			/* Build with given profile.  */
			else if (strcmp(long_options[option_index].name, "profile") == 0) {

				if (update_arg((void *)&(args_info->profile_arg), &(args_info->profile_orig),
							   &(args_info->profile_given), &(local_args_info.profile_given), optarg, 0, 0, ARG_STRING,
							   check_ambiguity, override, 0, 0, "profile", '-', additional_error)) {
					goto failure;
				}

			}
			/* Directory for all generated artifacts.  */
			else if (strcmp(long_options[option_index].name, "target-dir") == 0) {

				if (update_arg((void *)&(args_info->target_dir_arg), &(args_info->target_dir_orig),
							   &(args_info->target_dir_given), &(local_args_info.target_dir_given), optarg, 0, 0,
							   ARG_STRING, check_ambiguity, override, 0, 0, "target-dir", '-', additional_error)) {
					goto failure;
				}

			}
			/* Output build graph in JSON.  */
			else if (strcmp(long_options[option_index].name, "unit-graph") == 0) {

				if (update_arg((void *)&(args_info->unit_graph_flag), 0, &(args_info->unit_graph_given),
							   &(local_args_info.unit_graph_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override,
							   1, 0, "unit-graph", '-', additional_error)) {
					goto failure;
				}

			}
			/* Ignore `rust-version` specification in packages.  */
			else if (strcmp(long_options[option_index].name, "ignore-rust-version") == 0) {

				if (update_arg((void *)&(args_info->ignore_rust_version_flag), 0,
							   &(args_info->ignore_rust_version_given), &(local_args_info.ignore_rust_version_given),
							   optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0, "ignore-rust-version", '-',
							   additional_error)) {
					goto failure;
				}

			}
			/* Output build timing information.  */
			else if (strcmp(long_options[option_index].name, "timings") == 0) {

				if (update_arg((void *)&(args_info->timings_arg), &(args_info->timings_orig),
							   &(args_info->timings_given), &(local_args_info.timings_given), optarg, 0, 0, ARG_STRING,
							   check_ambiguity, override, 0, 0, "timings", '-', additional_error)) {
					goto failure;
				}

			}
			/* Outputs a future incompatibility report.  */
			else if (strcmp(long_options[option_index].name, "future-incompat-report") == 0) {

				if (update_arg((void *)&(args_info->future_incompat_report_flag), 0,
							   &(args_info->future_incompat_report_given),
							   &(local_args_info.future_incompat_report_given), optarg, 0, 0, ARG_FLAG, check_ambiguity,
							   override, 1, 0, "future-incompat-report", '-', additional_error)) {
					goto failure;
				}

			}
			/* Build all packages in the workspace.  */
			else if (strcmp(long_options[option_index].name, "workspace") == 0) {

				if (update_arg((void *)&(args_info->workspace_flag), 0, &(args_info->workspace_given),
							   &(local_args_info.workspace_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1,
							   0, "workspace", '-', additional_error)) {
					goto failure;
				}

			}
			/* Exclude packages from the build.  */
			else if (strcmp(long_options[option_index].name, "exclude") == 0) {

				if (update_arg((void *)&(args_info->exclude_arg), &(args_info->exclude_orig),
							   &(args_info->exclude_given), &(local_args_info.exclude_given), optarg, 0, 0, ARG_STRING,
							   check_ambiguity, override, 0, 0, "exclude", '-', additional_error)) {
					goto failure;
				}

			}
			/* Include packages in the build.  */
			else if (strcmp(long_options[option_index].name, "include") == 0) {

				if (update_arg((void *)&(args_info->include_arg), &(args_info->include_orig),
							   &(args_info->include_given), &(local_args_info.include_given), optarg, 0, 0, ARG_STRING,
							   check_ambiguity, override, 0, 0, "include", '-', additional_error)) {
					goto failure;
				}

			}
			/* Build only this package's library.  */
			else if (strcmp(long_options[option_index].name, "lib") == 0) {

				if (update_arg((void *)&(args_info->lib_flag), 0, &(args_info->lib_given), &(local_args_info.lib_given),
							   optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0, "lib", '-', additional_error)) {
					goto failure;
				}

			}
			/* Require Cargo.lock is up to date.  */
			else if (strcmp(long_options[option_index].name, "locked") == 0) {

				if (update_arg((void *)&(args_info->locked_flag), 0, &(args_info->locked_given),
							   &(local_args_info.locked_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0,
							   "locked", '-', additional_error)) {
					goto failure;
				}

			}
			/* Run without accessing the network.  */
			else if (strcmp(long_options[option_index].name, "offline") == 0) {

				if (update_arg((void *)&(args_info->offline_flag), 0, &(args_info->offline_given),
							   &(local_args_info.offline_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1,
							   0, "offline", '-', additional_error)) {
					goto failure;
				}

			}
			/* Equivalent to both --locked and --offline.  */
			else if (strcmp(long_options[option_index].name, "frozen") == 0) {

				if (update_arg((void *)&(args_info->frozen_flag), 0, &(args_info->frozen_given),
							   &(local_args_info.frozen_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0,
							   "frozen", '-', additional_error)) {
					goto failure;
				}

			}
			/* Override a configuration value.  */
			else if (strcmp(long_options[option_index].name, "config") == 0) {

				if (update_arg((void *)&(args_info->config_arg), &(args_info->config_orig), &(args_info->config_given),
							   &(local_args_info.config_given), optarg, 0, 0, ARG_STRING, check_ambiguity, override, 0,
							   0, "config", '-', additional_error)) {
					goto failure;
				}

			}
			/* Add as a development dependency.  */
			else if (strcmp(long_options[option_index].name, "dev") == 0) {

				if (update_arg((void *)&(args_info->dev_flag), 0, &(args_info->dev_given), &(local_args_info.dev_given),
							   optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0, "dev", '-', additional_error)) {
					goto failure;
				}

			}
			/* Add as a build dependency.  */
			else if (strcmp(long_options[option_index].name, "build") == 0) {

				if (update_arg((void *)&(args_info->build_flag), 0, &(args_info->build_given),
							   &(local_args_info.build_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0,
							   "build", '-', additional_error)) {
					goto failure;
				}

			}
			/* Mark dependency as optional.  */
			else if (strcmp(long_options[option_index].name, "optional") == 0) {

				if (update_arg((void *)&(args_info->optional_flag), 0, &(args_info->optional_given),
							   &(local_args_info.optional_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1,
							   0, "optional", '-', additional_error)) {
					goto failure;
				}

			}
			/* Mark dependency as required.  */
			else if (strcmp(long_options[option_index].name, "no-optional") == 0) {

				if (update_arg((void *)&(args_info->no_optional_flag), 0, &(args_info->no_optional_given),
							   &(local_args_info.no_optional_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override,
							   1, 0, "no-optional", '-', additional_error)) {
					goto failure;
				}

			}
			/* Rename the dependency.  */
			else if (strcmp(long_options[option_index].name, "rename") == 0) {

				if (update_arg((void *)&(args_info->rename_arg), &(args_info->rename_orig), &(args_info->rename_given),
							   &(local_args_info.rename_given), optarg, 0, 0, ARG_STRING, check_ambiguity, override, 0,
							   0, "rename", '-', additional_error)) {
					goto failure;
				}

			}
			/* Filesystem path to local dependency.  */
			else if (strcmp(long_options[option_index].name, "path") == 0) {

				if (update_arg((void *)&(args_info->path_arg), &(args_info->path_orig), &(args_info->path_given),
							   &(local_args_info.path_given), optarg, 0, 0, ARG_STRING, check_ambiguity, override, 0, 0,
							   "path", '-', additional_error)) {
					goto failure;
				}

			}
			/* Git repository location.  */
			else if (strcmp(long_options[option_index].name, "git") == 0) {

				if (update_arg((void *)&(args_info->git_arg), &(args_info->git_orig), &(args_info->git_given),
							   &(local_args_info.git_given), optarg, 0, 0, ARG_STRING, check_ambiguity, override, 0, 0,
							   "git", '-', additional_error)) {
					goto failure;
				}

			}
			/* Git branch to download.  */
			else if (strcmp(long_options[option_index].name, "branch") == 0) {

				if (update_arg((void *)&(args_info->branch_arg), &(args_info->branch_orig), &(args_info->branch_given),
							   &(local_args_info.branch_given), optarg, 0, 0, ARG_STRING, check_ambiguity, override, 0,
							   0, "branch", '-', additional_error)) {
					goto failure;
				}

			}
			/* Git tag to download.  */
			else if (strcmp(long_options[option_index].name, "tag") == 0) {

				if (update_arg((void *)&(args_info->tag_arg), &(args_info->tag_orig), &(args_info->tag_given),
							   &(local_args_info.tag_given), optarg, 0, 0, ARG_STRING, check_ambiguity, override, 0, 0,
							   "tag", '-', additional_error)) {
					goto failure;
				}

			}
			/* Git commit reference to download.  */
			else if (strcmp(long_options[option_index].name, "rev") == 0) {

				if (update_arg((void *)&(args_info->rev_arg), &(args_info->rev_orig), &(args_info->rev_given),
							   &(local_args_info.rev_given), optarg, 0, 0, ARG_STRING, check_ambiguity, override, 0, 0,
							   "rev", '-', additional_error)) {
					goto failure;
				}

			}
			/* Package registry for this dependency.  */
			else if (strcmp(long_options[option_index].name, "registry") == 0) {

				if (update_arg((void *)&(args_info->registry_arg), &(args_info->registry_orig),
							   &(args_info->registry_given), &(local_args_info.registry_given), optarg, 0, 0,
							   ARG_STRING, check_ambiguity, override, 0, 0, "registry", '-', additional_error)) {
					goto failure;
				}

			}
			/* Don't actually write the manifest.  */
			else if (strcmp(long_options[option_index].name, "dry-run") == 0) {

				if (update_arg((void *)&(args_info->dry_run_flag), 0, &(args_info->dry_run_given),
							   &(local_args_info.dry_run_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1,
							   0, "dry-run", '-', additional_error)) {
					goto failure;
				}

			}
			/* Output directory for artifacts.  */
			else if (strcmp(long_options[option_index].name, "out-dir") == 0) {

				if (update_arg((void *)&(args_info->out_dir_arg), &(args_info->out_dir_orig),
							   &(args_info->out_dir_given), &(local_args_info.out_dir_given), optarg, 0, 0, ARG_STRING,
							   check_ambiguity, override, 0, 0, "out-dir", '-', additional_error)) {
					goto failure;
				}

			}
			/* Output the build plan in JSON.  */
			else if (strcmp(long_options[option_index].name, "build-plan") == 0) {

				if (update_arg((void *)&(args_info->build_plan_flag), 0, &(args_info->build_plan_given),
							   &(local_args_info.build_plan_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override,
							   1, 0, "build-plan", '-', additional_error)) {
					goto failure;
				}

			}
			/* Continue building as much as possible.  */
			else if (strcmp(long_options[option_index].name, "keep-going") == 0) {

				if (update_arg((void *)&(args_info->keep_going_flag), 0, &(args_info->keep_going_given),
							   &(local_args_info.keep_going_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override,
							   1, 0, "keep-going", '-', additional_error)) {
					goto failure;
				}

			}
			/* Build all binary targets.  */
			else if (strcmp(long_options[option_index].name, "bins") == 0) {

				if (update_arg((void *)&(args_info->bins_flag), 0, &(args_info->bins_given),
							   &(local_args_info.bins_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0,
							   "bins", '-', additional_error)) {
					goto failure;
				}

			}
			/* Build all example targets.  */
			else if (strcmp(long_options[option_index].name, "examples") == 0) {

				if (update_arg((void *)&(args_info->examples_flag), 0, &(args_info->examples_given),
							   &(local_args_info.examples_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1,
							   0, "examples", '-', additional_error)) {
					goto failure;
				}

			}
			/* Build all test targets.  */
			else if (strcmp(long_options[option_index].name, "tests") == 0) {

				if (update_arg((void *)&(args_info->tests_flag), 0, &(args_info->tests_given),
							   &(local_args_info.tests_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0,
							   "tests", '-', additional_error)) {
					goto failure;
				}

			}
			/* Build all bench targets.  */
			else if (strcmp(long_options[option_index].name, "benches") == 0) {

				if (update_arg((void *)&(args_info->benches_flag), 0, &(args_info->benches_given),
							   &(local_args_info.benches_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1,
							   0, "benches", '-', additional_error)) {
					goto failure;
				}

			}
			/* Build all targets.  */
			else if (strcmp(long_options[option_index].name, "all-targets") == 0) {

				if (update_arg((void *)&(args_info->all_targets_flag), 0, &(args_info->all_targets_given),
							   &(local_args_info.all_targets_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override,
							   1, 0, "all-targets", '-', additional_error)) {
					goto failure;
				}

			}
			/* Don't run the generated binaries.  */
			else if (strcmp(long_options[option_index].name, "no-run") == 0) {

				if (update_arg((void *)&(args_info->no_run_flag), 0, &(args_info->no_run_given),
							   &(local_args_info.no_run_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override, 1, 0,
							   "no-run", '-', additional_error)) {
					goto failure;
				}

			}
			/* Run all tests regardless of failure.  */
			else if (strcmp(long_options[option_index].name, "no-fail-fast") == 0) {

				if (update_arg((void *)&(args_info->no_fail_fast_flag), 0, &(args_info->no_fail_fast_given),
							   &(local_args_info.no_fail_fast_given), optarg, 0, 0, ARG_FLAG, check_ambiguity, override,
							   1, 0, "no-fail-fast", '-', additional_error)) {
					goto failure;
				}

			}
			/* Toolchain used.  */
			else if (strcmp(long_options[option_index].name, "toolchain") == 0) {

				if (update_arg((void *)&(args_info->toolchain_arg), &(args_info->toolchain_orig),
							   &(args_info->toolchain_given), &(local_args_info.toolchain_given), optarg,
							   cmdline_parser_toolchain_values, 0, ARG_ENUM, check_ambiguity, override, 0, 0,
							   "toolchain", '-', additional_error)) {
					goto failure;
				}

			}
			/* command.  */
			else if (strcmp(long_options[option_index].name, "command") == 0) {

				if (update_arg((void *)&(args_info->command_arg), &(args_info->command_orig),
							   &(args_info->command_given), &(local_args_info.command_given), optarg, 0, 0, ARG_STRING,
							   check_ambiguity, override, 0, 0, "command", '-', additional_error)) {
					goto failure;
				}
			}

			break;
		case '?': /* Invalid option.  */
			/* `getopt_long' already printed an error message.  */
			goto failure;

		default: /* bug: option not considered.  */
			fprintf(stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c,
					(additional_error ? additional_error : ""));
			abort();
		} /* switch */
	} /* while */

	FIX_UNUSED(check_required);

	cmdline_parser_release(&local_args_info);

	if (error_occurred) {
		return (EXIT_FAILURE);
	}

	if (optind < argc) {
		int i				= 0;
		int found_prog_name = 0;
		/* whether program name, i.e., argv[0], is in the remaining args
		   (this may happen with some implementations of getopt,
			but surely not with the one included by gengetopt) */

		i = optind;
		while (i < argc) {
			if (argv[i++] == argv[0]) {
				found_prog_name = 1;
				break;
			}
		}
		i = 0;

		args_info->inputs_num = argc - optind - found_prog_name;
		args_info->inputs	  = (char **)(malloc((args_info->inputs_num) * sizeof(char *)));
		while (optind < argc) {
			if (argv[optind++] != argv[0]) {
				args_info->inputs[i++] = gengetopt_strdup(argv[optind - 1]);
			}
		}
	}

	return 0;

failure:

	cmdline_parser_release(&local_args_info);
	return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
