#include "dep_graph.h"

#include "safe.h"
#include "strings.h"

#include <stdio.h>

#include <sds/sds.h>
#include <sys/stat.h>
#include <toml.h>
#include <unistd.h>

/* ------------------------------------------------------------------ */
/* Graph cache — read / write to .coffee/build-cache/                   */
/* ------------------------------------------------------------------ */

static i64 dep_graph_cache_write(const dep_graph_t *g, const char *cache_path, i64 toml_mtime, i64 lock_mtime)
{
	/* Write to a temp file, fsync, then rename over the target so a crash
	 * or ENOSPC mid-write cannot truncate a previously valid cache. */
	sds   tmp_path = sdscatprintf(sdsempty(), "%s.tmp", cache_path);
	FILE *fp       = safe_fopen(tmp_path, "w");
	if (fp == nullptr) {
		sdsfree(tmp_path);
		return -1;
	}

	fprintf_safe(fp, "# This file is automatically generated by coffee.\n");
	fprintf_safe(fp, "# It caches the resolved dependency graph for faster builds.\n");
	fprintf_safe(fp, "[metadata]\n");
	fprintf_safe(fp, "coffee_toml_mtime = %lld\n", (long long)toml_mtime);
	fprintf_safe(fp, "coffee_lock_mtime = %lld\n", (long long)lock_mtime);
	fprintf_safe(fp, "cache_version = 2\n");
	fprintf_safe(fp, "offline = %s\n", (int)g->offline ? "true" : "false");

	for (size_t i = 0; i < g->count; i++) {
		dep_node_t *n = &g->nodes[i];
		fprintf_safe(fp, "\n[[nodes]]\n");
		fprintf_safe(fp, "name = \"%s\"\n", n->name != nullptr ? n->name : "");

		if (n->path != nullptr) {
			sds esc = toml_escape(n->path);
			fprintf_safe(fp, "path = \"%s\"\n", esc);
			sdsfree(esc);
		}
		if (n->version != nullptr) {
			sds esc = toml_escape(n->version);
			fprintf_safe(fp, "version = \"%s\"\n", esc);
			sdsfree(esc);
		}
		if (n->version_constraint != nullptr) {
			sds esc = toml_escape(n->version_constraint);
			fprintf_safe(fp, "version_constraint = \"%s\"\n", esc);
			sdsfree(esc);
		}
		if (n->commit != nullptr) {
			sds esc = toml_escape(n->commit);
			fprintf_safe(fp, "commit = \"%s\"\n", esc);
			sdsfree(esc);
		}
		fprintf_safe(fp, "is_git = %s\n", (int)n->is_git ? "true" : "false");
		if (n->git_ref != nullptr) {
			sds esc = toml_escape(n->git_ref);
			fprintf_safe(fp, "git_ref = \"%s\"\n", esc);
			sdsfree(esc);
		}
		if (n->flags != nullptr) {
			sds esc = toml_escape(n->flags);
			fprintf_safe(fp, "flags = \"%s\"\n", esc);
			sdsfree(esc);
		}
		if (n->src_count > 0 && n->sources != nullptr) {
			fprintf_safe(fp, "sources = [");
			for (size_t j = 0; j < n->src_count; j++) {
				sds esc = toml_escape(n->sources[j]);
				fprintf_safe(fp, "\"%s\"%s", esc, (j + 1 < n->src_count) ? ", " : "");
				sdsfree(esc);
			}
			fprintf_safe(fp, "]\n");
		}
	}

	if (fflush(fp) != 0) {
		safe_fclose(fp);
		remove(tmp_path);
		sdsfree(tmp_path);
		return -1;
	}
	if (fsync(fileno(fp)) != 0) {
		safe_fclose(fp);
		remove(tmp_path);
		sdsfree(tmp_path);
		return -1;
	}
	if (safe_fclose(fp) != 0) {
		remove(tmp_path);
		sdsfree(tmp_path);
		return -1;
	}
	if (safe_rename(tmp_path, cache_path) != 0) {
		remove(tmp_path);
		sdsfree(tmp_path);
		return -1;
	}
	safe_fsync_dir(cache_path);
	sdsfree(tmp_path);
	return 0;
}

static dep_graph_t *dep_graph_load_cached(const char *cache_path, i64 toml_mtime, i64 lock_mtime)
{
	FILE *fp = safe_fopen(cache_path, "r");
	if (fp == nullptr) {
		return nullptr;
	}

	char          errbuf[256];
	toml_table_t *conf = toml_parse_file(fp, errbuf, sizeof(errbuf));
	safe_fclose(fp);

	if (conf == nullptr) {
		return nullptr;
	}

	/* Validate metadata */
	toml_table_t *meta = toml_table_in(conf, "metadata");
	if (meta == nullptr) {
		toml_free(conf);
		return nullptr;
	}

	toml_datum_t cached_ver = toml_int_in(meta, "cache_version");
	if (!cached_ver.ok || cached_ver.u.i != 2) {
		toml_free(conf);
		return nullptr;
	}

	toml_datum_t cached_toml_mtime = toml_int_in(meta, "coffee_toml_mtime");
	if (!cached_toml_mtime.ok || cached_toml_mtime.u.i != toml_mtime) {
		toml_free(conf);
		return nullptr;
	}

	toml_datum_t cached_lock_mtime = toml_int_in(meta, "coffee_lock_mtime");
	if (!cached_lock_mtime.ok || cached_lock_mtime.u.i != lock_mtime) {
		toml_free(conf);
		return nullptr;
	}

	/* Read nodes */
	toml_array_t *nodes_arr = toml_array_in(conf, "nodes");
	if (nodes_arr == nullptr) {
		toml_free(conf);
		return nullptr;
	}

	i64 ncount = toml_array_nelem(nodes_arr);
	if (ncount <= 0) {
		toml_free(conf);
		return nullptr;
	}

	dep_graph_t *g = safe_calloc(1, sizeof(dep_graph_t));
	if (g == nullptr) {
		toml_free(conf);
		return nullptr;
	}

	g->capacity = (size_t)ncount;
	g->nodes    = safe_calloc(g->capacity, sizeof(dep_node_t));
	if (g->nodes == nullptr) {
		safe_free(g);
		toml_free(conf);
		return nullptr;
	}

	/* Read offline flag from metadata */
	toml_datum_t cached_offline = toml_bool_in(meta, "offline");
	if (cached_offline.ok != 0) {
		g->offline = (cached_offline.u.b != 0);
	} else {
		g->offline = false;
	}

	for (i64 i = 0; i < ncount; i++) {
		toml_table_t *ntbl = toml_table_at(nodes_arr, i);
		if (ntbl == nullptr) {
			continue;
		}

		toml_datum_t name_d = toml_string_in(ntbl, "name");
		if (name_d.ok) {
			g->nodes[i].name = sdsnew(name_d.u.s);
			safe_free(name_d.u.s);
		}

		toml_datum_t path_d = toml_string_in(ntbl, "path");
		if (path_d.ok) {
			g->nodes[i].path = sdsnew(path_d.u.s);
			safe_free(path_d.u.s);
		}

		toml_datum_t ver_d = toml_string_in(ntbl, "version");
		if (ver_d.ok) {
			g->nodes[i].version = sdsnew(ver_d.u.s);
			safe_free(ver_d.u.s);
		}

		toml_datum_t vc_d = toml_string_in(ntbl, "version_constraint");
		if (vc_d.ok) {
			g->nodes[i].version_constraint = sdsnew(vc_d.u.s);
			safe_free(vc_d.u.s);
		}

		toml_datum_t commit_d = toml_string_in(ntbl, "commit");
		if (commit_d.ok) {
			g->nodes[i].commit = sdsnew(commit_d.u.s);
			safe_free(commit_d.u.s);
		}

		toml_datum_t git_d = toml_bool_in(ntbl, "is_git");
		if (git_d.ok != 0) {
			g->nodes[i].is_git = (git_d.u.b != 0);
		} else {
			g->nodes[i].is_git = false;
		}

		toml_datum_t ref_d = toml_string_in(ntbl, "git_ref");
		if (ref_d.ok) {
			g->nodes[i].git_ref = sdsnew(ref_d.u.s);
			safe_free(ref_d.u.s);
		}

		toml_datum_t flags_d = toml_string_in(ntbl, "flags");
		if (flags_d.ok) {
			g->nodes[i].flags = sdsnew(flags_d.u.s);
			safe_free(flags_d.u.s);
		}

		toml_array_t *src_arr = toml_array_in(ntbl, "sources");
		if (src_arr != nullptr) {
			i64 src_count = toml_array_nelem(src_arr);
			if (src_count > 0) {
				g->nodes[i].sources   = safe_calloc((size_t)src_count, sizeof(sds));
				g->nodes[i].src_count = 0;
				if (g->nodes[i].sources != nullptr) {
					for (i64 j = 0; j < src_count; j++) {
						toml_datum_t s = toml_string_at(src_arr, j);
						if (s.ok) {
							g->nodes[i].sources[g->nodes[i].src_count] = sdsnew(s.u.s);
							g->nodes[i].src_count++;
							safe_free(s.u.s);
						}
					}
				}
			}
		}
	}

	g->count = (size_t)ncount;
	toml_free(conf);
	return g;
}

dep_graph_t *dep_graph_get(manifest_t *m, lockfile_t *lf, bool offline, const char *project_dir)
{
	if (m == nullptr) {
		return nullptr;
	}
	if (project_dir == nullptr) {
		return dep_graph_create(m, lf, offline);
	}

	/* Stat Coffee.toml and Coffee.lock for cache validation */
	i64 toml_mtime = 0;
	i64 lock_mtime = 0;

	/* Use nanosecond mtimes so two edits within the same second (common in
	 * scripts and CI) still invalidate the cache. */
	struct stat st;
	sds         toml_path = sdscatprintf(sdsempty(), "%s/Coffee.toml", project_dir);
	if (safe_stat(toml_path, &st) == 0) {
		toml_mtime = (i64)st.st_mtim.tv_sec * 1000000000 + st.st_mtim.tv_nsec;
	}
	sdsfree(toml_path);

	sds lock_path = sdscatprintf(sdsempty(), "%s/Coffee.lock", project_dir);
	if (safe_stat(lock_path, &st) == 0) {
		lock_mtime = (i64)st.st_mtim.tv_sec * 1000000000 + st.st_mtim.tv_nsec;
	}
	sdsfree(lock_path);

	/* Build cache path — create directory tree if needed */
	sds coffee_dir = sdscatprintf(sdsempty(), "%s/.coffee", project_dir);
	mkdir(coffee_dir, 0755);

	sds cache_dir = sdscatprintf(sdsempty(), "%s/build-cache", coffee_dir);
	mkdir(cache_dir, 0755);

	sdsfree(coffee_dir);

	const char *pkg_name   = m->package.name != nullptr ? m->package.name : "unnamed";
	sds         cache_path = sdscatprintf(sdsempty(), "%s/%s.graph", cache_dir, pkg_name);

	/* Try cache */
	dep_graph_t *g = dep_graph_load_cached(cache_path, toml_mtime, lock_mtime);
	if (g != nullptr) {
		sdsfree(cache_path);
		sdsfree(cache_dir);
		return g;
	}

	/* Cache miss — build from scratch */
	g = dep_graph_create(m, lf, offline);
	if (g != nullptr) {
		dep_graph_cache_write(g, cache_path, toml_mtime, lock_mtime);
	}

	sdsfree(cache_path);
	sdsfree(cache_dir);
	return g;
}
