#include "lockfile.h"

#include "safe.h"
#include "strings.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <toml.h>
#include <unistd.h>

lockfile_t *lockfile_parse(sds path)
{
	FILE *fp = safe_fopen(path, "r");
	if (fp == nullptr) {
		return nullptr;
	}

	char          errbuf[256];
	toml_table_t *conf = toml_parse_file(fp, errbuf, sizeof(errbuf));
	safe_fclose(fp);

	if (conf == nullptr) {
		return nullptr;
	}

	lockfile_t *lf = safe_calloc(1, sizeof(lockfile_t));
	if (lf == nullptr) {
		toml_free(conf);
		return nullptr;
	}

	/* Read version */
	toml_datum_t ver = toml_int_in(conf, "version");
	if (ver.ok) {
		lf->version = ver.u.i;
	} else {
		lf->version = 1;
	}

	/* Read [package] */
	toml_table_t *pkg = toml_table_in(conf, "package");
	if (pkg) {
		toml_datum_t name = toml_string_in(pkg, "name");
		if (name.ok) {
			lf->package_name = sdsnew(name.u.s);
			safe_free(name.u.s);
		}
		toml_datum_t pkg_ver = toml_string_in(pkg, "version");
		if (pkg_ver.ok) {
			lf->package_version = sdsnew(pkg_ver.u.s);
			safe_free(pkg_ver.u.s);
		}
	}

	/* Read [[dependencies]] */
	toml_array_t *deps_arr = toml_array_in(conf, "dependencies");
	if (deps_arr) {
		i64 n = toml_array_nelem(deps_arr);
		if (n > 0) {
			lf->deps = safe_calloc((size_t)n, sizeof(lockfile_dep_t));
			if (lf->deps == nullptr) {
				lockfile_free(lf);
				toml_free(conf);
				return nullptr;
			}
			/* Use a separate write index so skipped (non-table) slots do
			 * not leave NULL holes that inflate deps_count. */
			size_t idx = 0;
			for (i64 i = 0; i < n; i++) {
				toml_table_t *dep_tbl = toml_table_at(deps_arr, i);
				if (dep_tbl == nullptr) {
					continue;
				}
				toml_datum_t dep_name = toml_string_in(dep_tbl, "name");
				if (dep_name.ok) {
					lf->deps[idx].name = sdsnew(dep_name.u.s);
					safe_free(dep_name.u.s);
				}
				toml_datum_t dep_ver = toml_string_in(dep_tbl, "version");
				if (dep_ver.ok) {
					lf->deps[idx].version = sdsnew(dep_ver.u.s);
					safe_free(dep_ver.u.s);
				}
				toml_datum_t dep_path = toml_string_in(dep_tbl, "path");
				if (dep_path.ok) {
					lf->deps[idx].path = sdsnew(dep_path.u.s);
					safe_free(dep_path.u.s);
				}
				toml_datum_t dep_commit = toml_string_in(dep_tbl, "commit");
				if (dep_commit.ok) {
					lf->deps[idx].commit = sdsnew(dep_commit.u.s);
					safe_free(dep_commit.u.s);
				}
				idx++;
			}
			lf->deps_count = idx;
		}
	}

	toml_free(conf);
	return lf;
}

void lockfile_free(lockfile_t *lf)
{
	if (lf == nullptr) {
		return;
	}
	sdsfree(lf->package_name);
	sdsfree(lf->package_version);
	for (size_t i = 0; i < lf->deps_count; i++) {
		sdsfree(lf->deps[i].name);
		sdsfree(lf->deps[i].version);
		sdsfree(lf->deps[i].path);
		sdsfree(lf->deps[i].commit);
	}
	safe_free(lf->deps);
	safe_free(lf);
}

i64 lockfile_write(sds path, lockfile_t *lf)
{
	if (lf == nullptr || path == nullptr) {
		return -1;
	}

	/* Write to a temp file, fsync, then rename over the target so a crash
	 * or ENOSPC mid-write cannot truncate the user's Coffee.lock. */
	sds   tmp_path = sdscatprintf(sdsempty(), "%s.tmp", path);
	FILE *fp       = safe_fopen(tmp_path, "w");
	if (fp == nullptr) {
		sdsfree(tmp_path);
		return -1;
	}

	fprintf_safe(fp, "# This file is automatically generated by coffee.\n");
	fprintf_safe(fp, "# It locks dependency paths for reproducible builds.\n");
	fprintf_safe(fp, "version = %lld\n\n", (long long)lf->version);

	fprintf_safe(fp, "[package]\n");
	if (lf->package_name) {
		fprintf_toml_value(fp, "name = \"%s\"\n", lf->package_name);
	}
	if (lf->package_version) {
		fprintf_toml_value(fp, "version = \"%s\"\n", lf->package_version);
	}

	for (size_t i = 0; i < lf->deps_count; i++) {
		fprintf_safe(fp, "\n[[dependencies]]\n");
		if (lf->deps[i].name) {
			fprintf_toml_value(fp, "name = \"%s\"\n", lf->deps[i].name);
		}
		if (lf->deps[i].version) {
			fprintf_toml_value(fp, "version = \"%s\"\n", lf->deps[i].version);
		}
		if (lf->deps[i].path) {
			fprintf_toml_value(fp, "path = \"%s\"\n", lf->deps[i].path);
		}
		if (lf->deps[i].commit) {
			fprintf_toml_value(fp, "commit = \"%s\"\n", lf->deps[i].commit);
		}
	}

	if (fflush(fp) != 0) {
		safe_fclose(fp);
		remove(tmp_path);
		sdsfree(tmp_path);
		return -1;
	}
	if (fsync(fileno(fp)) != 0) {
		safe_fclose(fp);
		remove(tmp_path);
		sdsfree(tmp_path);
		return -1;
	}
	if (safe_fclose(fp) != 0) {
		remove(tmp_path);
		sdsfree(tmp_path);
		return -1;
	}
	if (safe_rename(tmp_path, path) != 0) {
		remove(tmp_path);
		sdsfree(tmp_path);
		return -1;
	}
	safe_fsync_dir(path);
	sdsfree(tmp_path);
	return 0;
}

lockfile_dep_t *lockfile_find_dep(lockfile_t *lf, const char *name)
{
	if (lf == nullptr || name == nullptr) {
		return nullptr;
	}
	for (size_t i = 0; i < lf->deps_count; i++) {
		if (lf->deps[i].name != nullptr && strcmp(lf->deps[i].name, name) == 0) {
			return &lf->deps[i];
		}
	}
	return nullptr;
}
