#include "lockfile.h"

#include "strings.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <toml.h>

lockfile_t *lockfile_parse(sds path)
{
	FILE *fp = fopen(path, "r");
	if (fp == nullptr) {
		return nullptr;
	}

	char          errbuf[256];
	toml_table_t *conf = toml_parse_file(fp, errbuf, sizeof(errbuf));
	fclose(fp);

	if (conf == nullptr) {
		return nullptr;
	}

	lockfile_t *lf = calloc(1, sizeof(lockfile_t));
	if (lf == nullptr) {
		toml_free(conf);
		return nullptr;
	}

	/* Read version */
	toml_datum_t ver = toml_int_in(conf, "version");
	if (ver.ok) {
		lf->version = ver.u.i;
	} else {
		lf->version = 1;
	}

	/* Read [package] */
	toml_table_t *pkg = toml_table_in(conf, "package");
	if (pkg) {
		toml_datum_t name = toml_string_in(pkg, "name");
		if (name.ok) {
			lf->package_name = sdsnew(name.u.s);
			free(name.u.s);
		}
		toml_datum_t pkg_ver = toml_string_in(pkg, "version");
		if (pkg_ver.ok) {
			lf->package_version = sdsnew(pkg_ver.u.s);
			free(pkg_ver.u.s);
		}
	}

	/* Read [[dependencies]] */
	toml_array_t *deps_arr = toml_array_in(conf, "dependencies");
	if (deps_arr) {
		lf->deps_count = (size_t)toml_array_nelem(deps_arr);
		if (lf->deps_count > 0) {
			lf->deps = calloc(lf->deps_count, sizeof(lockfile_dep_t));
			if (lf->deps == nullptr) {
				lockfile_free(lf);
				toml_free(conf);
				return nullptr;
			}
			for (size_t i = 0; i < lf->deps_count; i++) {
				toml_table_t *dep_tbl = toml_table_at(deps_arr, (i64)i);
				if (dep_tbl == nullptr) {
					continue;
				}
				toml_datum_t dep_name = toml_string_in(dep_tbl, "name");
				if (dep_name.ok) {
					lf->deps[i].name = sdsnew(dep_name.u.s);
					free(dep_name.u.s);
				}
				toml_datum_t dep_ver = toml_string_in(dep_tbl, "version");
				if (dep_ver.ok) {
					lf->deps[i].version = sdsnew(dep_ver.u.s);
					free(dep_ver.u.s);
				}
				toml_datum_t dep_path = toml_string_in(dep_tbl, "path");
				if (dep_path.ok) {
					lf->deps[i].path = sdsnew(dep_path.u.s);
					free(dep_path.u.s);
				}
			}
		}
	}

	toml_free(conf);
	return lf;
}

void lockfile_free(lockfile_t *lf)
{
	if (lf == nullptr) {
		return;
	}
	sdsfree(lf->package_name);
	sdsfree(lf->package_version);
	for (size_t i = 0; i < lf->deps_count; i++) {
		sdsfree(lf->deps[i].name);
		sdsfree(lf->deps[i].version);
		sdsfree(lf->deps[i].path);
	}
	free(lf->deps);
	free(lf);
}

i64 lockfile_write(sds path, lockfile_t *lf)
{
	if (lf == nullptr || path == nullptr) {
		return -1;
	}

	FILE *fp = fopen(path, "w");
	if (fp == nullptr) {
		return -1;
	}

	fprintf_safe(fp, "# This file is automatically generated by coffee.\n");
	fprintf_safe(fp, "# It locks dependency paths for reproducible builds.\n");
	fprintf_safe(fp, "version = %lld\n\n", (long long)lf->version);

	fprintf_safe(fp, "[package]\n");
	if (lf->package_name) {
		fprintf_safe(fp, "name = \"%s\"\n", lf->package_name);
	}
	if (lf->package_version) {
		fprintf_safe(fp, "version = \"%s\"\n", lf->package_version);
	}

	for (size_t i = 0; i < lf->deps_count; i++) {
		fprintf_safe(fp, "\n[[dependencies]]\n");
		if (lf->deps[i].name) {
			fprintf_safe(fp, "name = \"%s\"\n", lf->deps[i].name);
		}
		if (lf->deps[i].version) {
			fprintf_safe(fp, "version = \"%s\"\n", lf->deps[i].version);
		}
		if (lf->deps[i].path) {
			fprintf_safe(fp, "path = \"%s\"\n", lf->deps[i].path);
		}
	}

	fclose(fp);
	return 0;
}

lockfile_dep_t *lockfile_find_dep(lockfile_t *lf, const char *name)
{
	if (lf == nullptr || name == nullptr) {
		return nullptr;
	}
	for (size_t i = 0; i < lf->deps_count; i++) {
		if (lf->deps[i].name != nullptr && strcmp(lf->deps[i].name, name) == 0) {
			return &lf->deps[i];
		}
	}
	return nullptr;
}
